"""make demo parse run rounds nullable

Revision ID: 7701acd7d8c8
Revises: 627a2c7ebdd7
Create Date: 2026-05-24 21:31:14.614332

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7701acd7d8c8'
down_revision: Union[str, Sequence[str], None] = '627a2c7ebdd7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('demo_parse_runs', 'rounds_count',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('demo_parse_runs', 'rounds_count',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###
