"""create demo bomb round stats

Revision ID: 7cbb69a1fd55
Revises: eccacf6697af
Create Date: 2026-06-03 14:24:54.985858

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7cbb69a1fd55'
down_revision: Union[str, Sequence[str], None] = 'eccacf6697af'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('demo_bomb_round_stats',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('parse_run_id', sa.UUID(), nullable=False),
    sa.Column('round_number', sa.Integer(), nullable=False),
    sa.Column('planter_name', sa.String(length=255), nullable=True),
    sa.Column('planter_team_name', sa.String(length=255), nullable=True),
    sa.Column('defuser_name', sa.String(length=255), nullable=True),
    sa.Column('defuser_team_name', sa.String(length=255), nullable=True),
    sa.Column('outcome', sa.String(length=50), nullable=False),
    sa.Column('plant_tick', sa.Integer(), nullable=True),
    sa.Column('defuse_tick', sa.Integer(), nullable=True),
    sa.Column('explosion_tick', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['parse_run_id'], ['demo_parse_runs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_demo_bomb_round_stats_parse_run_id'), 'demo_bomb_round_stats', ['parse_run_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_demo_bomb_round_stats_parse_run_id'), table_name='demo_bomb_round_stats')
    op.drop_table('demo_bomb_round_stats')
    # ### end Alembic commands ###
