"""create demo player damage stats

Revision ID: eccacf6697af
Revises: 7701acd7d8c8
Create Date: 2026-05-30 19:26:19.365365

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'eccacf6697af'
down_revision: Union[str, Sequence[str], None] = '7701acd7d8c8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('demo_player_damage_stats',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('parse_run_id', sa.UUID(), nullable=False),
    sa.Column('player_name', sa.String(length=255), nullable=False),
    sa.Column('team_name', sa.String(length=255), nullable=True),
    sa.Column('total_damage', sa.Integer(), nullable=False),
    sa.Column('rounds_count', sa.Integer(), nullable=False),
    sa.Column('average_damage_per_round', sa.Float(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['parse_run_id'], ['demo_parse_runs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_demo_player_damage_stats_parse_run_id'), 'demo_player_damage_stats', ['parse_run_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_demo_player_damage_stats_parse_run_id'), table_name='demo_player_damage_stats')
    op.drop_table('demo_player_damage_stats')
    # ### end Alembic commands ###
