import {useMemo,useState} from "react";
import {createAnalystFactor,deleteAnalystFactor,updateAnalystFactor} from "../api";
import type {AnalystCategory,AnalystEnvironment,AnalystFactor,AnalystFactorPayload,TeamParticipant} from "../types";

const maps=["ancient","anubis","dust2","inferno","mirage","nuke","overpass","train","vertigo"];
const categories:AnalystCategory[]=["overall","ct_defense","t_attack","tactics","veto","form","communication","roles","individual","teamplay","mental","coach","roster","other"];
const categoryLabel=(value:string|null)=>value??"—";
const empty=(teamId:number):AnalystFactorPayload=>({team_id:teamId,factor_type:"positive",text:"",category:null,map_name:null,environment:"any",player_ids:[],coach_id:null,valid_from:null,valid_until:null,is_active:true});
const toLocalInput=(value:string|null)=>{if(!value)return null;const date=new Date(value);const offset=date.getTimezoneOffset()*60_000;return new Date(date.getTime()-offset).toISOString().slice(0,16)};
const toUtc=(value:string|null)=>value?new Date(value).toISOString():null;

export function AnalystFactorsPanel({teamId,roster,initial}:{teamId:number;roster:TeamParticipant[];initial:AnalystFactor[]}){
 const [items,setItems]=useState(initial);const [editing,setEditing]=useState<AnalystFactor|null|"new">(null);const [form,setForm]=useState(empty(teamId));const [error,setError]=useState<string|null>(null);
 const [type,setType]=useState("all"),[map,setMap]=useState("all"),[person,setPerson]=useState("all"),[env,setEnv]=useState("all"),[category,setCategory]=useState("all"),[status,setStatus]=useState("all");
 const players=roster.filter(p=>p.participant_type==="player"&&p.is_active&&!p.left_at),coaches=roster.filter(p=>p.participant_type==="coach"&&p.is_active&&!p.left_at);
 const visible=useMemo(()=>items.filter(x=>(type==="all"||x.factor_type===type)&&(map==="all"||(map==="all_maps"?!x.map_name:x.map_name===map))&&(person==="all"||(person.startsWith("coach:")?x.coach?.id===Number(person.slice(6)):x.players.some(p=>p.id===Number(person))))&&(env==="all"||x.environment===env)&&(category==="all"||x.category===category)&&(status==="all"||x.status===status)),[items,type,map,person,env,category,status]);
 function open(item?:AnalystFactor){setError(null);if(item){setEditing(item);setForm({team_id:teamId,factor_type:item.factor_type,text:item.text,category:item.category,map_name:item.map_name,environment:item.environment,player_ids:item.players.map(p=>p.id),coach_id:item.coach?.id??null,valid_from:toLocalInput(item.valid_from),valid_until:toLocalInput(item.valid_until),is_active:item.is_active})}else{setEditing("new");setForm(empty(teamId))}}
 async function save(e:React.FormEvent){e.preventDefault();setError(null);try{const payload={...form,valid_from:toUtc(form.valid_from),valid_until:toUtc(form.valid_until)};const saved=editing==="new"?await createAnalystFactor(payload):await updateAnalystFactor((editing as AnalystFactor).id,payload);setItems(current=>editing==="new"?[saved,...current]:current.map(x=>x.id===saved.id?saved:x));setEditing(null)}catch(value){setError(value instanceof Error?value.message:"Не удалось сохранить фактор")}}
 async function remove(item:AnalystFactor){if(!window.confirm("Удалить аналитический фактор?"))return;await deleteAnalystFactor(item.id);setItems(x=>x.filter(v=>v.id!==item.id))}
 async function toggle(item:AnalystFactor){const saved=await updateAnalystFactor(item.id,{is_active:!item.is_active});setItems(x=>x.map(v=>v.id===item.id?saved:v))}
 return <section className="strength-panel analyst-factors"><div className="section-heading"><div><p className="eyebrow">Human qualitative context · не влияет на ML</p><h2>Аналитические плюсы и минусы</h2></div><button className="button button--primary" onClick={()=>open()}>Добавить аналитический фактор</button></div>
 <div className="analyst-filters"><select aria-label="Тип" value={type} onChange={e=>setType(e.target.value)}><option value="all">Все</option><option value="positive">Плюсы</option><option value="negative">Минусы</option></select><select aria-label="Карта" value={map} onChange={e=>setMap(e.target.value)}><option value="all">Все карты и фильтры</option><option value="all_maps">Только «Все карты»</option>{maps.map(x=><option key={x}>{x}</option>)}</select><select aria-label="Игрок или тренер" value={person} onChange={e=>setPerson(e.target.value)}><option value="all">Все игроки / тренеры</option>{players.map(x=><option value={x.id} key={x.id}>{x.nickname}</option>)}{coaches.map(x=><option value={`coach:${x.id}`} key={`c${x.id}`}>Coach: {x.nickname}</option>)}</select><select aria-label="Среда" value={env} onChange={e=>setEnv(e.target.value)}><option value="all">Любая среда</option><option value="lan">LAN</option><option value="online">Online</option><option value="any">Any</option></select><select aria-label="Категория" value={category} onChange={e=>setCategory(e.target.value)}><option value="all">Все категории</option>{categories.map(x=><option key={x}>{categoryLabel(x)}</option>)}</select><select aria-label="Статус" value={status} onChange={e=>setStatus(e.target.value)}><option value="all">Все статусы</option><option value="active">Активные</option><option value="expired">Истёкшие</option><option value="inactive">Отключённые</option><option value="scheduled">Запланированные</option></select></div>
 {visible.length?<div className="analyst-table"><div className="analyst-row analyst-row--head"><span>Тип</span><span>Категория</span><span>Игроки / тренер</span><span>Карта</span><span>Среда</span><span>Комментарий</span><span></span></div>{visible.map(x=><div className={`analyst-row analyst-row--${x.status}`} key={x.id}><span><b className={`analyst-badge analyst-badge--${x.factor_type}`}>{x.factor_type==="positive"?"+":"−"}</b></span><span>{categoryLabel(x.category)}</span><span>{[...x.players.map(p=>p.nickname),...(x.coach?[`Coach: ${x.coach.nickname}`]:[])].join(", ")||"—"}</span><span>{x.map_name??"Все"}</span><span>{x.environment==="any"?"Любая":x.environment.toUpperCase()}</span><span>{x.text}<small>{x.status==="expired"?"Истёк":x.status==="inactive"?"Отключён":x.status==="scheduled"?"Запланирован":"Активен"}</small></span><span className="analyst-actions"><button onClick={()=>open(x)}>Изменить</button><button onClick={()=>void toggle(x)}>{x.is_active?"Отключить":"Включить"}</button><button onClick={()=>void remove(x)}>Удалить</button></span></div>)}</div>:<div className="empty-state">Факторы по выбранным фильтрам не найдены.</div>}
 {editing&&<div className="analyst-modal" role="dialog" aria-modal="true"><form onSubmit={save}><div className="section-heading"><h2>{editing==="new"?"Новый аналитический фактор":"Редактирование фактора"}</h2><button type="button" onClick={()=>setEditing(null)}>×</button></div>{error&&<div className="notice notice--error">{error}</div>}<div className="analyst-form-grid"><label>Тип<select value={form.factor_type} onChange={e=>setForm({...form,factor_type:e.target.value as AnalystFactorPayload["factor_type"]})}><option value="positive">Плюс</option><option value="negative">Минус</option></select></label><label>Категория<select value={form.category??""} onChange={e=>setForm({...form,category:(e.target.value||null) as AnalystCategory|null})}><option value="">Без категории</option>{categories.map(x=><option key={x}>{x}</option>)}</select></label><fieldset><legend>Игроки</legend>{players.map(x=><label key={x.id}><input type="checkbox" checked={form.player_ids.includes(x.id)} onChange={e=>setForm({...form,player_ids:e.target.checked?[...form.player_ids,x.id]:form.player_ids.filter(id=>id!==x.id)})}/>{x.nickname}</label>)}</fieldset><label>Тренер<select value={form.coach_id??""} onChange={e=>setForm({...form,coach_id:e.target.value?Number(e.target.value):null})}><option value="">Не выбран</option>{coaches.map(x=><option value={x.id} key={x.id}>{x.nickname}</option>)}</select></label><label>Карта<select value={form.map_name??""} onChange={e=>setForm({...form,map_name:e.target.value||null})}><option value="">Все карты</option>{maps.map(x=><option key={x}>{x}</option>)}</select></label><label>Среда<select value={form.environment} onChange={e=>setForm({...form,environment:e.target.value as AnalystEnvironment})}><option value="any">Любая</option><option value="lan">LAN</option><option value="online">Online</option></select></label><label>Актуален с<input type="datetime-local" value={form.valid_from??""} onChange={e=>setForm({...form,valid_from:e.target.value||null})}/></label><label>Актуален до<input type="datetime-local" value={form.valid_until??""} onChange={e=>setForm({...form,valid_until:e.target.value||null})}/></label><label className="analyst-comment">Комментарий<textarea required rows={5} value={form.text} onChange={e=>setForm({...form,text:e.target.value})}/></label></div><div className="modal-actions"><button type="button" className="button" onClick={()=>setEditing(null)}>Отмена</button><button className="button button--primary">Сохранить</button></div></form></div>}</section>
}
