import {useEffect,useState} from "react";
import {getOpponentContext} from "../api";
import type {FormContext} from "../types";

const rows=[['Tournament Form','tournament_form_score','Форма именно в текущем турнире с учётом силы соперников и качества серий.'],['Adjusted Form (60d)','recent_60d_adjusted_form_score','Форма за последние 60 дней с поправкой на силу календаря.'],['Strength of Schedule','strength_of_schedule_score','Насколько сильные соперники были в недавних матчах.'],['Performance vs Expectation','performance_vs_expectation_score','Насколько команда сыграла лучше или хуже ожидаемого уровня.']] as const;

export function TeamFormContextBlock({context}:{context:FormContext}){return <section className="strength-panel"><div className="section-heading"><div><p className="eyebrow">Opponent-adjusted context</p><h2>Form Context</h2></div><span>{context.recent_60d_matches_count} серий за 60 дней</span></div>{context.status==="insufficient_data"?<div className="empty-state">Недостаточно недавних серий для надёжной оценки формы.</div>:<div className="team-match-summary">{rows.map(([label,key,help])=><article key={key}><span title={help}>{label}</span><strong>{context[key]?.toFixed(1)??"—"}</strong>{key==="tournament_form_score"&&<small>{context.tournament_matches_count} серий</small>}</article>)}</div>}<p className="formula">Только матчи до {context.as_of}; матчи одного дня изолированы. Надёжность {(context.recent_60d_reliability*100).toFixed(0)}%.</p></section>}

export function CompareFormContextBlock({teamA,teamB,nameA,nameB,teamAId,teamBId}:{teamA:FormContext;teamB:FormContext;nameA:string;nameB:string;teamAId?:number;teamBId?:number}){const [dynamic,setDynamic]=useState<any>(null);useEffect(()=>{if(teamAId&&teamBId)Promise.all([getOpponentContext(teamAId),getOpponentContext(teamBId)]).then(([a,b])=>setDynamic({a,b})).catch(()=>setDynamic(null))},[teamAId,teamBId]);return <section className="map-pool-comparison"><div className="section-heading"><div><p className="eyebrow">Opponent-adjusted context</p><h2>Form Context</h2></div><span>v1 production · v2 candidate</span></div><div className="map-pool-table"><div className="map-pool-row map-pool-row--head"><span>Показатель</span><span>{nameA}</span><span>{nameB}</span><span>Смысл</span></div>{rows.map(([label,key,help])=><div className="map-pool-row" key={key}><strong title={help}>{label}</strong><span>{teamA[key]?.toFixed(1)??'Недостаточно данных'}</span><span>{teamB[key]?.toFixed(1)??'Недостаточно данных'}</span><small>{help}</small></div>)}{dynamic&&<><div className="map-pool-row"><strong>Raw recent form</strong><span>{dynamic.a.raw_form_score.toFixed(1)}</span><span>{dynamic.b.raw_form_score.toFixed(1)}</span><small>Доля побед без поправки</small></div><div className="map-pool-row"><strong>Opponent-adjusted v2</strong><span>{dynamic.a.opponent_adjusted_form_score.toFixed(1)}</span><span>{dynamic.b.opponent_adjusted_form_score.toFixed(1)}</span><small>Candidate: сила соперника именно на дату серии</small></div><div className="map-pool-row"><strong>Dynamic SoS</strong><span>{dynamic.a.dynamic_sos_score?.toFixed(1)??"—"}</span><span>{dynamic.b.dynamic_sos_score?.toFixed(1)??"—"}</span><small>Средняя temporal-safe сила соперников</small></div></>}</div><p className="formula">60 дней: {teamA.recent_60d_matches_count} / {teamB.recent_60d_matches_count} серий · Tournament: {teamA.tournament_matches_count} / {teamB.tournament_matches_count}. Результаты текущей и same-day серий не используются.</p></section>}
