import { useEffect, useState } from "react";
import { getTeamMapDetail, getTeamMapsV3, getTeamMapV3 } from "../api";
import type { MapStrengthV3Item, MapV3Metric, MapV3Results, PerformanceProfile, TeamMapAggregate } from "../types";

const number = (v: number | null | undefined) => v == null ? "—" : v.toFixed(2);
const delta = (v: number | null) => v == null ? "—" : `${v >= 0 ? "+" : ""}${number(v)}`;
const labels: Record<string,string> = {results_quality:"Results Quality",side_performance:"Side Performance",map_execution:"Map Execution",round_winrate:"Round winrate",opening:"Opening",economy:"Full-buy / Economy",retake:"Retake",postplant:"Postplant",conversion_recovery:"Conversion / Recovery",conversion:"Advantage conversion",recovery:"Disadvantage recovery",full_buy:"Full-buy",force_buy:"Force-buy",anti_eco:"Anti-eco",pistol_conversion:"Pistol conversion",trading:"Trading",utility:"Utility",entrying:"Entrying",top_1_10:"Top 1–10",top_11_20:"Top 11–20",top_21_30:"Top 21–30",others:"Others",unknown:"Unknown"};
function Score({value,label}:{value:number|null;label:string}) {return <div className="map-v35-score"><span>{label}</span><meter min={0} max={100} value={value??0} aria-label={label}/><b>{number(value)}{value!=null&&" /100"}</b></div>}
function Metric({name,value}:{name:string;value:MapV3Metric}) {return <details className="map-v35-metric"><summary><b>{labels[name]??name}</b><span>{number(value.score)}</span><small>Reliability {number(value.reliability)}%{value.sample_size!=null&&` · sample ${number(value.sample_size)}`}</small></summary><p>Вес {number((value.weight??0)*100)}% · доступный вес {number((value.effective_weight??0)*100)}%</p>{value.score==null&&<p>Unavailable — {value.unavailable_reason??"нет доступных метрик"}</p>}{value.plant_opportunities!=null&&<p>Plant opportunities: {number(value.plant_opportunities)} · Plants: {number(value.plants)}</p>}{value.diagnostics&&<details><summary>Диагностика экономики</summary>{Object.entries(value.diagnostics).map(([k,v])=><p key={k}>{k}: {number(v.score)} · sample {number(v.sample_size)} · reliability {number(v.reliability)}%</p>)}<p>Reset recovery: unavailable</p></details>}{value.metrics&&Object.entries(value.metrics).map(([k,v])=><Metric key={k} name={k} value={v}/>)}</details>}
function Results({value}:{value:MapV3Results}) {return <span>{value.maps} maps · {value.wins}/{value.losses} W/L · RD {delta(value.round_differential)} · Adjusted {number(value.score)}</span>}
function Profile({profile}:{profile:PerformanceProfile}) {
 const [scope,setScope]=useState<"overall"|"ct"|"t">("overall");
 return <section><h3>Map Performance Profile</h3><p>Диагностика: Firepower, Sniping и Clutching не имеют отдельного веса в Map Strength.</p><div className="performance-tabs">{(["overall","ct","t"] as const).map(s=><button className={scope===s?"button button--primary":"button"} key={s} onClick={()=>setScope(s)}>{s==="overall"?"Both":s.toUpperCase()}</button>)}</div>{Object.entries(profile.scopes[scope]).map(([name,m])=><details key={name}><summary><Score label={name} value={m.score}/></summary><p>Reliability {number(m.reliability)}% · sample {m.sample_size}</p>{m.score==null&&<p>Unavailable</p>}{m.breakdown.map(b=><p key={b.key}>{b.key}: raw {number(b.raw_value)}, score {number(b.normalized_score)}, weight {number(b.effective_weight*100)}%</p>)}</details>)}</section>
}
function Details({item}:{item:MapStrengthV3Item}) {return <div className="map-v35-details">
 <details open><summary><h3>1. Results Quality — {number(item.components.results_quality.score)}</h3></summary><Metric name="results_quality" value={item.components.results_quality}/><p>Overall: <Results value={item.results_breakdown.overall}/></p>{Object.entries(item.results_breakdown.groups).map(([k,v])=><p key={k}><b>{labels[k]}</b>: <Results value={v}/></p>)}</details>
 <details open><summary><h3>2. Side Performance — {number(item.components.side_performance.score)}</h3></summary><p>CT и T: 50/50 при наличии обеих сторон.</p>{(["ct","t"] as const).map(s=><section key={s}><Score label={`${s.toUpperCase()} SIDE`} value={item.sides[s].score}/><p>Reliability {number(item.sides[s].reliability)}% · {item.sides[s].rounds} applicable rounds</p>{Object.entries(item.sides[s].metrics??{}).map(([k,v])=><Metric key={k} name={k} value={v}/>)}</section>)}</details>
 <details open><summary><h3>3. Map Execution — {number(item.components.map_execution.score)}</h3></summary>{Object.entries(item.components.map_execution.metrics??{}).map(([k,v])=><Metric key={k} name={k} value={v}/>)}</details>
 <Profile profile={item.performance_profile}/><details><summary>Sample / Reliability / Roster</summary>{Object.entries(item.sample).map(([k,v])=><p key={k}>{k}: {v}</p>)}{Object.entries(item.reliability_breakdown).map(([k,v])=><p key={k}>{k}: {number(v*100)}%</p>)}<p>Roster: {item.roster_context.effective_player_ids.join(" / ")} · {item.roster_context.source}</p>{item.roster_context.replacements.map(r=><p key={r.id}>{r.player_in.nickname} вместо {r.player_out.nickname}</p>)}{item.roster_context.warnings.map(w=><p key={w}>{w}</p>)}</details>
 </div>}
function Card({item,legacy,teamId,expanded=false}:{item:MapStrengthV3Item;legacy?:number|null;teamId:number;expanded?:boolean}) {return <article className="map-v35-card"><h3>{item.map} <small>{item.is_active_pool?"Active pool":"Historical map"}</small></h3><Score label="New Map Strength V3" value={item.score}/><p>Team baseline: <b>{number(item.team_strength_v3)}</b> · Map delta: <b>{delta(item.delta_vs_team)}</b></p><p><b>{item.status}</b> {item.flags.join(" · ")} · Reliability <b>{number(item.reliability)}%</b></p><div className="map-v35-sides"><Score label="CT" value={item.sides.ct.score}/><Score label="T" value={item.sides.t.score}/></div><p>Legacy Map Strength: {number(legacy)}</p>{expanded?<Details item={item}/>:<a href={`/teams/${teamId}/maps/${encodeURIComponent(item.map)}${window.location.search}`}>Подробнее →</a>}</article>}
export function MapsV3Panel({teamId,legacy}:{teamId:number;legacy:TeamMapAggregate[]}) {
 const [maps,setMaps]=useState<MapStrengthV3Item[]|null>(null);const [error,setError]=useState<string|null>(null);
 useEffect(()=>{let active=true;setMaps(null);setError(null);getTeamMapsV3(teamId,window.location.search).then(v=>{if(active)setMaps(v.maps)}).catch(e=>{if(active)setError(String(e))});return()=>{active=false}},[teamId]);
 return <section className="strength-panel"><h2>Maps V3</h2><p>45% Results Quality + 25% Side Performance + 30% Map Execution</p>{error?<p role="alert">{error}</p>:maps===null?<p>Рассчитываю Map Strength V3…</p>:<div className="map-v35-grid">{[...maps].sort((a,b)=>Number(b.is_active_pool)-Number(a.is_active_pool)||(b.score??-1)-(a.score??-1)).map(m=><Card key={m.map} item={m} teamId={teamId} legacy={legacy.find(l=>l.map_name===m.map)?.strength.map_strength_score}/>)}</div>}</section>
}
export function MapV3Page({teamId,mapName}:{teamId:number;mapName:string}) {
 const [item,setItem]=useState<MapStrengthV3Item|null>(null);const [legacy,setLegacy]=useState<number|null>(null);const [error,setError]=useState<string|null>(null);
 useEffect(()=>{let active=true;getTeamMapV3(teamId,mapName,window.location.search).then(v=>{if(active)setItem(v.map_strength_v3)}).catch(e=>{if(active)setError(String(e))});getTeamMapDetail(teamId,mapName,"current_roster").then(v=>{if(active)setLegacy(v.strength.map_strength_score)}).catch(()=>{});return()=>{active=false}},[teamId,mapName]);
 return <main className="page"><a href={`/teams/${teamId}${window.location.search}`}>← Команда</a><h1>Map Strength V3 · {mapName}</h1>{error?<p role="alert">{error}</p>:item?<Card item={item} teamId={teamId} legacy={legacy} expanded/>:<p>Рассчитываю карту…</p>}</main>
}
