import {useEffect,useState} from "react";

import {ApiError,generateMatchLLMAnalysis,getLatestMatchLLMAnalysis,getMatchLLMAnalysisHistory,getMatchLLMAnalysisRun,regenerateMatchLLMAnalysis} from "../api";
import type {LLMMatchAnalysisContext,MatchLLMAnalysisRun,MatchLLMHistoryItem,MatchLLMAnalysisV3,MatchExplanationPlanV2} from "../types";
import {BettingRestrictionWarning} from "./BettingRestrictionWarning";

const errorLabels:Record<string,string>={llm_not_configured:"LLM provider не настроен.",llm_timeout:"Генерация заняла слишком много времени.",llm_provider_error:"LLM provider временно недоступен.",llm_invalid_response:"Модель вернула некорректный ответ.",llm_validation_failed:"Ответ модели не прошёл проверку фактов.",llm_grounding_failed:"Ответ модели содержал неподтверждённые факты."};

function pct(value:number|null){return value===null?null:`${(value*100).toFixed(1)}%`}
function dateTime(value:string){return new Date(value).toLocaleString("ru-RU",{dateStyle:"short",timeStyle:"short"})}
function teamName(context:LLMMatchAnalysisContext,side:string){return side==="team_a"?context.teams.team_a.name??"Команда A":side==="team_b"?context.teams.team_b.name??"Команда B":"Нет фаворита"}

const fixedSections:Array<[keyof Pick<MatchLLMAnalysisV3,"conclusion_text"|"form_text"|"maps_text"|"teamplay_text"|"manual_text">,string,string]>=[
  ["conclusion_text","📌","Итог"],["form_text","📈","Форма"],["maps_text","🗺","Карты"],["teamplay_text","🎯","Тимплей и свинги"],["manual_text","📝","Ручная аналитика"],
];
function FixedAnalysisView({analysis,plan}:{analysis:MatchLLMAnalysisV3;plan:MatchExplanationPlanV2|null}){const hasExpected=Boolean(plan&&Object.prototype.hasOwnProperty.call(plan,"expected_winner"));const expected=plan?.expected_winner;return <div className="llm-fixed-sections">{hasExpected&&<section className="llm-fixed-section llm-fixed-section--winner"><h3><span>🏆</span>Кто должен выиграть по расчётам</h3><p>{expected?`${expected.team_name} — ${pct(expected.win_probability)}`:"Расчёт победителя недоступен."}</p></section>}{fixedSections.map(([key,icon,title])=><section className="llm-fixed-section" key={key}><h3><span>{icon}</span>{title}</h3><p>{analysis[key]}</p></section>)}</div>}

export interface MatchLLMAnalysisPanelProps{teamAId:number;teamBId:number;matchId?:number;tournamentId?:number;matchFormat?:"bo1"|"bo3"|"bo5";asOf?:string}
export function MatchLLMAnalysisPanel({teamAId,teamBId,matchId,tournamentId,matchFormat,asOf}:MatchLLMAnalysisPanelProps){
  const [run,setRun]=useState<MatchLLMAnalysisRun|null>(null);const [latestId,setLatestId]=useState<number|null>(null);const [loading,setLoading]=useState(true);const [generating,setGenerating]=useState(false);const [error,setError]=useState<string|null>(null);const [historyOpen,setHistoryOpen]=useState(false);const [history,setHistory]=useState<MatchLLMHistoryItem[]>([]);const [historyLoading,setHistoryLoading]=useState(false);
  useEffect(()=>{let active=true;setLoading(true);setError(null);void getLatestMatchLLMAnalysis(teamAId,teamBId,matchId).then(value=>{if(active){setRun(value);setLatestId(value?.analysis_run_id??null)}}).catch(()=>{if(active)setError("Не удалось загрузить сохранённый AI-анализ.")}).finally(()=>{if(active)setLoading(false)});return()=>{active=false}},[teamAId,teamBId,matchId]);
  async function generate(){setGenerating(true);setError(null);try{const value=await generateMatchLLMAnalysis({team_a_id:teamAId,team_b_id:teamBId,as_of:asOf??new Date().toISOString(),...(matchId?{match_id:matchId}:{}),...(tournamentId?{tournament_id:tournamentId}:{}),...(matchFormat?{match_format:matchFormat}:{}),analysis_mode:"pre_match",language:"ru"});setRun(value);setLatestId(value.analysis_run_id)}catch(value){const code=value instanceof ApiError?value.code:null;setError(code&&errorLabels[code]?errorLabels[code]:"Не удалось получить AI-анализ. Попробуйте повторить генерацию.")}finally{setGenerating(false)}}
  async function openHistory(){setHistoryOpen(value=>!value);if(!historyOpen){setHistoryLoading(true);try{setHistory(await getMatchLLMAnalysisHistory(teamAId,teamBId,matchId))}catch{setError("Не удалось загрузить историю анализов.")}finally{setHistoryLoading(false)}}}
  async function selectHistory(id:number){try{setRun(await getMatchLLMAnalysisRun(id));setHistoryOpen(false)}catch{setError("Не удалось открыть сохранённую версию.")}}
  async function regenerate(){if(!run)return;setGenerating(true);setError(null);try{const value=await regenerateMatchLLMAnalysis(run.analysis_run_id);setRun(value);setLatestId(value.analysis_run_id)}catch{setError("Не удалось перегенерировать анализ на сохранённых данных.")}finally{setGenerating(false)}}
  if(loading)return <section className="llm-panel"><div className="llm-panel__loading">Загружаю AI-анализ…</div></section>;
  const rawAnalysis=run?.analysis;const context=run?.context;const fixedAnalysis=rawAnalysis?.schema_version==="match_llm_analysis.v3"?rawAnalysis:null;const fixedPlan=run?.explanation_plan?.schema_version==="match_explanation_plan.v2"?run.explanation_plan:null;const hasAnalysis=Boolean(fixedAnalysis);const historical=Boolean(run&&latestId&&run.analysis_run_id!==latestId);
  return <section className="llm-panel" aria-label="AI-анализ"><div className="section-heading"><div><p className="eyebrow">Объяснение прогноза CS2Eye</p><h2>AI-анализ</h2></div><div className="llm-panel__actions"><button type="button" className="button" onClick={()=>void openHistory()}>История анализов</button><button type="button" className="button button--primary" disabled={generating} onClick={()=>void generate()}>{generating?"Генерация анализа…":hasAnalysis?"Обновить анализ":"Сгенерировать анализ"}</button></div></div>
    {error&&<div className="llm-panel__error" role="alert">{error}</div>}
    {historyOpen&&<aside className="llm-history"><div><h3>История анализов</h3><button type="button" onClick={()=>setHistoryOpen(false)} aria-label="Закрыть историю">×</button></div>{historyLoading?<p>Загружаю историю…</p>:history.length===0?<p>Сохранённых запусков пока нет.</p>:<ul>{history.map(item=><li className={item.status==="failed"?"llm-history__failed":""} key={item.id}><button type="button" disabled={item.status==="failed"} onClick={()=>void selectHistory(item.id)}><strong>{dateTime(item.created_at)}</strong><span>{item.model??"Без вызова модели"} · {item.prompt_version.replace("match_analysis_prompt.","")}</span><span>{item.status==="failed"?"Ошибка генерации":`${teamName(run?.context??({teams:{team_a:{name:"Команда A"},team_b:{name:"Команда B"}}} as LLMMatchAnalysisContext),item.favored_team??"none")} · ${item.confidence??"—"}`}</span></button></li>)}</ul>}</aside>}
    {!hasAnalysis||!context?<div className="llm-panel__empty"><h3>AI-анализ ещё не создан</h3><p>Сначала CS2Eye рассчитает и сохранит контекст, затем LLM сформулирует пять готовых разделов.</p></div>:<>
      <BettingRestrictionWarning restriction={context.betting_restrictions}/>
      {historical&&<div className="llm-version-notice">Просматривается сохранённая версия от {dateTime(run.created_at)}.<button type="button" onClick={()=>latestId&&void selectHistory(latestId)}>Вернуться к последней</button></div>}
      {fixedAnalysis&&<FixedAnalysisView analysis={fixedAnalysis} plan={fixedPlan}/>}
      <footer className="llm-footer"><span>Сгенерировано: {dateTime(run.created_at)}</span><span>Model: {run.runtime.model}</span><span>Prompt: {run.runtime.prompt_version.replace("match_analysis_prompt.","")}</span>{historical&&<button type="button" className="button" disabled={generating} onClick={()=>void regenerate()}>Перегенерировать на тех же данных</button>}<details><summary>Техническая информация</summary><p>Provider: {run.runtime.provider} · attempts: {run.runtime.attempts} · tokens: {run.runtime.input_tokens??"—"}/{run.runtime.output_tokens??"—"}</p><p>Проверки: schema {String(run.runtime.schema_valid)}, business {String(run.runtime.business_valid)}, grounding {String(run.runtime.grounding_valid)}</p></details></footer>
    </>}
  </section>;
}
