import {cleanup,fireEvent,render,screen,waitFor} from "@testing-library/react";
import {afterEach,beforeEach,describe,expect,it,vi} from "vitest";

import {ApiError} from "../api";
import type {MatchLLMAnalysisRun} from "../types";
import {MatchLLMAnalysisPanel} from "./MatchLLMAnalysisPanel";

vi.mock("../api",async()=>{const actual=await vi.importActual<typeof import("../api")>("../api");return {...actual,getLatestMatchLLMAnalysis:vi.fn(),generateMatchLLMAnalysis:vi.fn(),getMatchLLMAnalysisHistory:vi.fn(),getMatchLLMAnalysisRun:vi.fn(),regenerateMatchLLMAnalysis:vi.fn()}});
import {generateMatchLLMAnalysis,getLatestMatchLLMAnalysis,getMatchLLMAnalysisHistory,getMatchLLMAnalysisRun,regenerateMatchLLMAnalysis} from "../api";

const latest=vi.mocked(getLatestMatchLLMAnalysis),generate=vi.mocked(generateMatchLLMAnalysis),history=vi.mocked(getMatchLLMAnalysisHistory),detail=vi.mocked(getMatchLLMAnalysisRun),regenerate=vi.mocked(regenerateMatchLLMAnalysis);

function fixture(overrides:Partial<MatchLLMAnalysisRun>={}):MatchLLMAnalysisRun{return {
  analysis_run_id:42,source_run_id:null,status:"completed",error_code:null,error_message:null,validation_error_codes:[],created_at:"2026-08-27T07:30:00Z",completed_at:"2026-08-27T07:31:00Z",
  runtime:{provider:"ollama",model:"qwen3:8b",prompt_version:"match_analysis_prompt.v5",attempts:1,input_tokens:500,output_tokens:180,provider_response_id:"hidden",schema_valid:true,business_valid:true,grounding_valid:true,repair_attempted:false,grounding_error_codes:[]},
  context:{schema_version:"match_analysis_context.v1",generated_at:"2026-08-27T07:29:00Z",as_of:"2026-08-26T00:00:00Z",analysis_mode:"pre_match",match:{id:160,date:"2026-08-28",format:"bo3",environment:"lan",stage:"semifinal",is_playoff:true,is_elimination:false,tournament:{id:7,name:"Test Cup",tier:"S"},round_number:3,round_label:"Semifinal",section:"main"},teams:{team_a:{id:8,name:"Aurora",rank:8,roster:{roster_id:80,players:[{id:81,name:"AuroraPlayer",role:"rifler"}],coach:null,stability_score:70,reliability:.7,sample_maps:10},team_strength:{score:72,reliability:.7,sample_size:10,key_factors:[]},form:{tournament_form_score:68,tournament_matches:3,tournament_reliability:.6,recent_60d_score:71,recent_60d_matches:8,recent_60d_reliability:.7,strength_of_schedule_score:74,performance_vs_expectation_score:2,matches_vs_top_5:1,matches_vs_top_10:2,matches_vs_top_30:7},leadership:{igl_score:70,coach_score:68,reliability:.6,sample_size:8}},team_b:{id:9,name:"G2",rank:10,roster:{roster_id:90,players:[{id:91,name:"G2Player",role:"awper"}],coach:null,stability_score:72,reliability:.72,sample_maps:11},team_strength:{score:75,reliability:.71,sample_size:11,key_factors:[]},form:{tournament_form_score:66,tournament_matches:3,tournament_reliability:.6,recent_60d_score:73,recent_60d_matches:9,recent_60d_reliability:.7,strength_of_schedule_score:76,performance_vs_expectation_score:3,matches_vs_top_5:2,matches_vs_top_10:4,matches_vs_top_30:8},leadership:{igl_score:71,coach_score:69,reliability:.6,sample_size:9}}},recent_series_evidence:{team_a:[{evidence_id:"series:168",date:"2026-08-25",tournament:"Test Cup",opponent:{id:10,name:"Falcons",rank:3},result:"win",series_score:"2-1",expected_win_probability:.34,performance_vs_expectation:.21,current_tournament:true,reliability:.8}],team_b:[]},prediction:{source_type:"ml_prediction",status:"available",model_version:"win.v1",quality_gate_passed:true,team_a_probability:.4186,team_b_probability:.5814,confidence:.62,top_model_drivers:[]},matchup:{source_type:"deterministic_analytics",model_version:"matchup.v2",team_a_score:51.13,team_b_score:48.87,reliability:.55,factors:[{factor_id:"matchup:form",key:"recent_form",team_a_score:52,team_b_score:48,reliability:.6,sample_size:7}]},veto:{source_type:"deterministic_analytics",basis:"calculated_veto",model_version:null,likely_maps:[]},map_matchups:[],h2h:{preferred_scope:"organizations",history_applicability:"low",organizations:{series_played:1},current_rosters:{series_played:0}},manual_context:{source_type:"manual_analyst_note",team_a:[{note_id:"note:1",polarity:"negative",category:"roster",players:[],coach:null,map:null,environment:"lan",text:"Команда выглядит уставшей."}],team_b:[]},data_quality:{overall_status:"weak",limitations:["Мало свежих серий"],missing_sections:["veto","map_matchups"],warnings:["Низкая надёжность карты"]}},
  explanation_plan:{schema_version:"match_explanation_plan.v2",context_schema_version:"match_analysis_context.v1",expected_winner:{team_id:9,team_name:"G2",win_probability:.58},conclusion:{team_a_name:"Aurora",team_b_name:"G2",favored_team:"team_b",advantage:"small",confidence:"medium",ml_probability_team_a:.4186,ml_probability_team_b:.5814,internal_statistics_disclaimer:"Преимущество основано на внутренней статистике CS2Eye."},form:{},maps:{},teamplay:{},manual_context:{}},
  analysis:{schema_version:"match_llm_analysis.v3",explanation_plan_version:"match_explanation_plan.v2",expected_winner_text:"По расчётам должна выиграть G2 — 58%.",conclusion_text:"G2 остаётся небольшим фаворитом по внутренней статистике CS2Eye.",form_text:"Турнирная форма описана только по переданным результатам команд.",maps_text:"Данных по картам недостаточно для уверенного сравнения.",teamplay_text:"Доступные различия в командной игре заранее отобраны внутренней аналитикой.",manual_text:"Ручные комментарии аналитика: команда Aurora выглядит уставшей."},
  ...overrides,
}}

beforeEach(()=>{vi.clearAllMocks();latest.mockResolvedValue(fixture());history.mockResolvedValue([])});
afterEach(cleanup);

describe("MatchLLMAnalysisPanel",()=>{
  it("shows the backend NAVI override above AI presentation",async()=>{const base=fixture();latest.mockResolvedValue(fixture({context:{...base.context,betting_restrictions:{restricted:true,rule:"navi_no_match_winner_bets",message:"НЕ СТАВИТЬ НА NAVI И НЕ СТАВИТЬ ПРОТИВ NAVI."}}}));render(<MatchLLMAnalysisPanel teamAId={8} teamBId={9}/>);const warning=await screen.findByRole("alert");expect(warning.textContent).toContain("NAVI RULE");expect(warning.textContent).toContain("НЕ СТАВИТЬ НА NAVI")});
  it("renders expected winner and all five fixed sections",async()=>{const base=fixture();render(<MatchLLMAnalysisPanel teamAId={8} teamBId={9}/>);for(const text of ["Кто должен выиграть по расчётам","G2 — 58.0%","Итог","Форма","Карты","Тимплей и свинги","Ручная аналитика",base.analysis!.conclusion_text,base.analysis!.form_text,base.analysis!.maps_text,base.analysis!.teamplay_text,base.analysis!.manual_text])expect(await screen.findByText(text)).toBeTruthy()});
  it("shows unavailable winner text when the plan has no expected winner",async()=>{const base=fixture();latest.mockResolvedValue(fixture({explanation_plan:{...base.explanation_plan!,expected_winner:null},analysis:{...base.analysis!,expected_winner_text:"Расчёт победителя недоступен."}}));render(<MatchLLMAnalysisPanel teamAId={8} teamBId={9}/>);expect(await screen.findByText("Расчёт победителя недоступен.")).toBeTruthy()});
  it("shows empty state and generate button",async()=>{latest.mockResolvedValue(null);render(<MatchLLMAnalysisPanel teamAId={8} teamBId={9}/>);expect(await screen.findByText("AI-анализ ещё не создан")).toBeTruthy();expect(screen.getByText("Сгенерировать анализ")).toBeTruthy()});
  it("disables generate while loading and reports safe errors",async()=>{latest.mockResolvedValue(null);let release:(value:MatchLLMAnalysisRun)=>void=()=>{};generate.mockImplementation(()=>new Promise(resolve=>{release=resolve}));render(<MatchLLMAnalysisPanel teamAId={8} teamBId={9}/>);const button=await screen.findByText("Сгенерировать анализ");fireEvent.click(button);expect(await screen.findByText("Генерация анализа…")).toBeTruthy();expect((screen.getByText("Генерация анализа…") as HTMLButtonElement).disabled).toBe(true);release(fixture());await screen.findByText("Итог");generate.mockRejectedValue(new ApiError(502,"llm_grounding_failed","internal"));fireEvent.click(screen.getByText("Обновить анализ"));expect(await screen.findByText("Ответ модели содержал неподтверждённые факты.")).toBeTruthy()});
  it("loads history, opens stored run without rebuilding and regenerates same context",async()=>{const old=fixture({analysis_run_id:30,created_at:"2026-08-20T10:00:00Z"});history.mockResolvedValue([{id:30,source_run_id:null,created_at:old.created_at,status:"completed",provider:"ollama",model:"qwen3:8b",prompt_version:"match_analysis_prompt.v5",as_of:old.context.as_of,analysis_status:"limited",favored_team:"team_b",confidence:"medium"},{id:31,source_run_id:null,created_at:"2026-08-21T10:00:00Z",status:"failed",provider:"ollama",model:"qwen3:8b",prompt_version:"match_analysis_prompt.v5",as_of:old.context.as_of,analysis_status:null,favored_team:null,confidence:null}]);detail.mockResolvedValue(old);regenerate.mockResolvedValue(fixture({analysis_run_id:50,source_run_id:30}));render(<MatchLLMAnalysisPanel teamAId={8} teamBId={9} matchId={160}/>);await screen.findByText("Итог");fireEvent.click(screen.getByText("История анализов"));expect(await screen.findByText("Ошибка генерации")).toBeTruthy();const oldDate=screen.getAllByText(/20\.08\.2026/)[0];fireEvent.click(oldDate.closest("button")!);expect(await screen.findByText(/Просматривается сохранённая версия/)).toBeTruthy();expect(latest).toHaveBeenCalledTimes(1);fireEvent.click(screen.getByText("Перегенерировать на тех же данных"));await waitFor(()=>expect(regenerate).toHaveBeenCalledWith(30));expect(generate).not.toHaveBeenCalled()});
});
