import {useEffect,useState} from "react";

import {ApiError,generateMatchLLMAnalysis,getLatestMatchLLMAnalysis,getMatchLLMAnalysisHistory,getMatchLLMAnalysisRun,regenerateMatchLLMAnalysis} from "../api";
import type {LLMAnalysisClaim,LLMAnalysisRisk,LLMDataLimitation,LLMMatchAnalysisContext,MatchLLMAnalysisRun,MatchLLMHistoryItem,MatchLLMAnalysisV1,MatchLLMAnalysisV2,MatchExplanationPlan} from "../types";

const advantageLabels={none:"преимущества нет",small:"небольшой фаворит",moderate:"заметный фаворит",clear:"явный фаворит"} as const;
const confidenceLabels={high:"высокая",medium:"средняя",low:"низкая",insufficient:"недостаточная"} as const;
const qualityLabels={available:"доступны",partial:"частичные",weak:"слабое качество данных",insufficient:"недостаточно данных"} as const;
const importanceLabels={high:"важно",medium:"средне",low:"дополнительно"} as const;
const categoryLabels:Record<string,string>={overall_strength:"общая сила",recent_form:"текущая форма",tournament_form:"форма на турнире",strength_of_schedule:"сила соперников",performance_vs_expectation:"игра относительно ожиданий",roster:"состав",map_pool:"набор карт",veto:"вето",ct_side:"сторона CT",t_side:"сторона T",economy:"экономика",opening:"первые дуэли",trade:"размены",clutch:"клатчи",postplant:"постплэнт",retake:"ретейки",leadership:"лидерство",h2h:"личные встречи",ml_prediction:"ML-прогноз",matchup:"Matchup Score",manual_context:"ручной контекст",data_quality:"качество данных",other:"другое"};
const errorLabels:Record<string,string>={llm_not_configured:"LLM provider не настроен.",llm_timeout:"Генерация заняла слишком много времени.",llm_provider_error:"LLM provider временно недоступен.",llm_invalid_response:"Модель вернула некорректный ответ.",llm_validation_failed:"Ответ модели не прошёл проверку фактов.",llm_grounding_failed:"Ответ модели содержал неподтверждённые факты."};

function pct(value:number|null){return value===null?null:`${(value*100).toFixed(1)}%`}
function dateTime(value:string){return new Date(value).toLocaleString("ru-RU",{dateStyle:"short",timeStyle:"short"})}
function teamName(context:LLMMatchAnalysisContext,side:string){return side==="team_a"?context.teams.team_a.name??"Команда A":side==="team_b"?context.teams.team_b.name??"Команда B":"Нет фаворита"}
function compactNumber(value:number|null|undefined){return value===null||value===undefined?"—":Number.isInteger(value)?String(value):value.toFixed(2)}

function normalizeV2(analysis:MatchLLMAnalysisV2,plan:MatchExplanationPlan):MatchLLMAnalysisV1{return {schema_version:"match_llm_analysis.v1",context_schema_version:"match_analysis_context.v1",analysis_status:plan.status,conclusion:{...plan.conclusion,reasoning_basis:"ml_prediction"},summary:analysis.summary,key_advantages:plan.advantages.filter(item=>analysis.advantage_texts[item.signal_id]).map(item=>({claim_id:item.signal_id,side:item.side,category:item.category,importance:item.importance,statement:analysis.advantage_texts[item.signal_id],evidence_refs:item.evidence_refs,evidence_kind:item.source_kind})),counter_arguments:plan.counter_arguments.filter(item=>analysis.counter_argument_texts[item.signal_id]).map(item=>({claim_id:item.signal_id,side:item.side,category:item.category,importance:item.importance,statement:analysis.counter_argument_texts[item.signal_id],evidence_refs:item.evidence_refs,evidence_kind:item.source_kind})),contradictions:plan.contradictions.filter(item=>analysis.contradiction_texts[item.contradiction_id]).map(item=>({contradiction_id:item.contradiction_id,importance:item.importance,description:analysis.contradiction_texts[item.contradiction_id],evidence_refs:[item.left_ref,item.right_ref]})),risks:plan.risks.filter(item=>analysis.risk_texts[item.risk_id]).map(item=>({risk_id:item.risk_id,severity:item.severity,category:item.category,statement:analysis.risk_texts[item.risk_id],evidence_refs:item.evidence_refs,evidence_kind:"deterministic"})),data_limitations:plan.limitations.filter(item=>analysis.limitation_texts[item.limitation_id]).map(item=>({limitation_id:item.limitation_id,severity:item.severity,statement:analysis.limitation_texts[item.limitation_id],evidence_refs:item.evidence_refs,evidence_kind:"data_quality"}))}}

export function resolveEvidence(ref:string,context:LLMMatchAnalysisContext):string[]{
  const prediction=context.prediction;
  if(ref==="prediction")return prediction.status==="available"?[`ML: ${teamName(context,"team_a")} ${pct(prediction.team_a_probability)} · ${teamName(context,"team_b")} ${pct(prediction.team_b_probability)}`,`Надёжность модели: ${pct(prediction.confidence)??"—"}`]:["ML-прогноз недоступен"];
  if(ref==="matchup")return [`Matchup: ${teamName(context,"team_a")} ${compactNumber(context.matchup.team_a_score)} · ${teamName(context,"team_b")} ${compactNumber(context.matchup.team_b_score)}`,`Надёжность: ${pct(context.matchup.reliability)??"—"}`];
  const matchupFactor=context.matchup.factors.find(item=>item.factor_id===ref);
  if(matchupFactor)return [`Фактор ${categoryLabels[matchupFactor.key]??matchupFactor.key}: ${compactNumber(matchupFactor.team_a_score)} / ${compactNumber(matchupFactor.team_b_score)}`,`Выборка: ${matchupFactor.sample_size??"—"} · надёжность ${pct(matchupFactor.reliability)??"—"}`];
  for(const side of ["team_a","team_b"] as const){const series=context.recent_series_evidence[side].find(item=>item.evidence_id===ref);if(series)return [`${teamName(context,side)} — ${series.result==="win"?"победа":"поражение"} против ${series.opponent.name??"неизвестного соперника"}${series.series_score?` ${series.series_score.replace("-",":")}`:""}`,`${series.tournament??"Турнир не указан"}${series.opponent.rank?` · рейтинг соперника #${series.opponent.rank}`:""}`,`Игра относительно ожиданий: ${compactNumber(series.performance_vs_expectation)}`]}
  for(const side of ["team_a","team_b"] as const){const team=context.teams[side];if(ref===`team:${team.id}:form`)return [`${teamName(context,side)}: форма за 60 дней ${compactNumber(team.form.recent_60d_score)}`,`Серий: ${team.form.recent_60d_matches} · надёжность ${pct(team.form.recent_60d_reliability)??"—"}`,`Форма на турнире: ${compactNumber(team.form.tournament_form_score)}`];if(ref===`team:${team.id}:strength`)return [`${teamName(context,side)}: сила команды ${compactNumber(team.team_strength.score)}`,`Выборка: ${team.team_strength.sample_size} · надёжность ${pct(team.team_strength.reliability)??"—"}`];if(ref===`team:${team.id}:roster`)return [`Состав ${teamName(context,side)}: ${team.roster.players.map(player=>player.name).join(", ")||"не указан"}`,`Стабильность: ${compactNumber(team.roster.stability_score)} · карт ${team.roster.sample_maps}`];if(ref===`team:${team.id}:leadership`)return [`${teamName(context,side)}: IGL ${compactNumber(team.leadership.igl_score)} · тренер ${compactNumber(team.leadership.coach_score)}`,`Выборка: ${team.leadership.sample_size}`]}
  for(const map of context.map_matchups){if(ref===`map:${map.map}`)return [`${map.map}: сила ${compactNumber(map.team_a.map_strength)} / ${compactNumber(map.team_b.map_strength)}`,`Релевантность: ${pct(map.relevance)??"—"}`];const edge=map.key_edges.find(item=>item.evidence_id===ref);if(edge)return [`${map.map}: ${categoryLabels[edge.metric]??edge.metric} в пользу ${teamName(context,edge.favored_team)}`,`Сила: ${edge.strength} · надёжность ${pct(edge.reliability)??"—"}`]}
  for(const side of ["team_a","team_b"] as const){const note=context.manual_context[side].find(item=>item.note_id===ref);if(note)return [`Ручная заметка аналитика о ${teamName(context,side)}`,note.text]}
  if(ref.startsWith("h2h:")){const scope=ref.endsWith("current_rosters")?context.h2h.current_rosters:context.h2h.organizations;const played=scope["series_played"];return [ref.endsWith("current_rosters")?"Личные встречи текущих составов":"История встреч организаций",typeof played==="number"?`Сыграно серий: ${played}`:`Применимость истории: ${context.h2h.history_applicability}`]}
  if(ref==="data_quality")return [`Качество данных: ${qualityLabels[context.data_quality.overall_status]}`,...context.data_quality.limitations.slice(0,2)];
  if(ref==="veto")return context.veto.likely_maps.length?[`Вероятные карты: ${context.veto.likely_maps.map(item=>item.map).join(", ")}`]:["Данные veto отсутствуют"];
  return ["Подтверждение сохранено в snapshot анализа."];
}

type Claim=LLMAnalysisClaim|LLMAnalysisRisk|LLMDataLimitation;
function ClaimCard({claim,context,kind}:{claim:Claim;context:LLMMatchAnalysisContext;kind:"claim"|"risk"|"limitation"}){const level="importance" in claim?claim.importance:claim.severity;const category="category" in claim?claim.category:"data_quality";return <article className={`llm-claim llm-claim--${level}`}><div className="llm-claim__meta"><span>{categoryLabels[category]??category}</span><span>{importanceLabels[level]}</span>{(claim.evidence_kind==="manual"||claim.evidence_kind==="mixed")&&<em>Ручной контекст</em>}</div><p>{claim.statement}</p><details className="llm-evidence"><summary>Почему такой вывод?</summary>{claim.evidence_refs.map(ref=><div key={ref}>{resolveEvidence(ref,context).map((line,index)=><span key={`${ref}-${index}`}>{line}</span>)}</div>)}</details></article>}

export interface MatchLLMAnalysisPanelProps{teamAId:number;teamBId:number;matchId?:number;tournamentId?:number;asOf?:string}
export function MatchLLMAnalysisPanel({teamAId,teamBId,matchId,tournamentId,asOf}:MatchLLMAnalysisPanelProps){
  const [run,setRun]=useState<MatchLLMAnalysisRun|null>(null);const [latestId,setLatestId]=useState<number|null>(null);const [loading,setLoading]=useState(true);const [generating,setGenerating]=useState(false);const [error,setError]=useState<string|null>(null);const [historyOpen,setHistoryOpen]=useState(false);const [history,setHistory]=useState<MatchLLMHistoryItem[]>([]);const [historyLoading,setHistoryLoading]=useState(false);
  useEffect(()=>{let active=true;setLoading(true);setError(null);void getLatestMatchLLMAnalysis(teamAId,teamBId,matchId).then(value=>{if(active){setRun(value);setLatestId(value?.analysis_run_id??null)}}).catch(()=>{if(active)setError("Не удалось загрузить сохранённый AI-анализ.")}).finally(()=>{if(active)setLoading(false)});return()=>{active=false}},[teamAId,teamBId,matchId]);
  async function generate(){setGenerating(true);setError(null);try{const value=await generateMatchLLMAnalysis({team_a_id:teamAId,team_b_id:teamBId,as_of:asOf??new Date().toISOString(),...(matchId?{match_id:matchId}:{}),...(tournamentId?{tournament_id:tournamentId}:{}),analysis_mode:"pre_match",language:"ru"});setRun(value);setLatestId(value.analysis_run_id)}catch(value){const code=value instanceof ApiError?value.code:null;setError(code&&errorLabels[code]?errorLabels[code]:"Не удалось получить AI-анализ. Попробуйте повторить генерацию.")}finally{setGenerating(false)}}
  async function openHistory(){setHistoryOpen(value=>!value);if(!historyOpen){setHistoryLoading(true);try{setHistory(await getMatchLLMAnalysisHistory(teamAId,teamBId,matchId))}catch{setError("Не удалось загрузить историю анализов.")}finally{setHistoryLoading(false)}}}
  async function selectHistory(id:number){try{setRun(await getMatchLLMAnalysisRun(id));setHistoryOpen(false)}catch{setError("Не удалось открыть сохранённую версию.")}}
  async function regenerate(){if(!run)return;setGenerating(true);setError(null);try{const value=await regenerateMatchLLMAnalysis(run.analysis_run_id);setRun(value);setLatestId(value.analysis_run_id)}catch{setError("Не удалось перегенерировать анализ на сохранённых данных.")}finally{setGenerating(false)}}
  if(loading)return <section className="llm-panel"><div className="llm-panel__loading">Загружаю AI-анализ…</div></section>;
  const rawAnalysis=run?.analysis;const context=run?.context;const analysis=rawAnalysis?.schema_version==="match_llm_analysis.v2"&&run?.explanation_plan?normalizeV2(rawAnalysis,run.explanation_plan):rawAnalysis as MatchLLMAnalysisV1|null|undefined;const historical=Boolean(run&&latestId&&run.analysis_run_id!==latestId);
  return <section className="llm-panel" aria-label="AI-анализ"><div className="section-heading"><div><p className="eyebrow">Объяснение прогноза CS2Eye</p><h2>AI-анализ</h2></div><div className="llm-panel__actions"><button type="button" className="button" onClick={()=>void openHistory()}>История анализов</button><button type="button" className="button button--primary" disabled={generating} onClick={()=>void generate()}>{generating?"Генерация анализа…":analysis?"Обновить анализ":"Сгенерировать анализ"}</button></div></div>
    {error&&<div className="llm-panel__error" role="alert">{error}</div>}
    {historyOpen&&<aside className="llm-history"><div><h3>История анализов</h3><button type="button" onClick={()=>setHistoryOpen(false)} aria-label="Закрыть историю">×</button></div>{historyLoading?<p>Загружаю историю…</p>:history.length===0?<p>Сохранённых запусков пока нет.</p>:<ul>{history.map(item=><li className={item.status==="failed"?"llm-history__failed":""} key={item.id}><button type="button" disabled={item.status==="failed"} onClick={()=>void selectHistory(item.id)}><strong>{dateTime(item.created_at)}</strong><span>{item.model??"Без вызова модели"} · {item.prompt_version.replace("match_analysis_prompt.","")}</span><span>{item.status==="failed"?"Ошибка генерации":`${teamName(run?.context??({teams:{team_a:{name:"Команда A"},team_b:{name:"Команда B"}}} as LLMMatchAnalysisContext),item.favored_team??"none")} · ${item.confidence??"—"}`}</span></button></li>)}</ul>}</aside>}
    {!analysis||!context?<div className="llm-panel__empty"><h3>AI-анализ ещё не создан</h3><p>Сначала CS2Eye рассчитает и сохранит контекст, затем LLM объяснит готовый ML-прогноз.</p></div>:<>
      {historical&&<div className="llm-version-notice">Просматривается сохранённая версия от {dateTime(run.created_at)}.<button type="button" onClick={()=>latestId&&void selectHistory(latestId)}>Вернуться к последней</button></div>}
      <div className="llm-verdict"><div><small>Фаворит по ML</small><strong>{analysis.conclusion.favored_team==="none"?"Фаворит не определён":`${teamName(context,analysis.conclusion.favored_team)} — ${advantageLabels[analysis.conclusion.advantage]}`}</strong><span>LLM объясняет прогноз, но не рассчитывает вероятность.</span></div><div className="llm-probability"><small>ML prediction</small>{context.prediction.status==="available"&&context.prediction.team_a_probability!==null&&context.prediction.team_b_probability!==null?<><b>{teamName(context,"team_a")} {pct(context.prediction.team_a_probability)}</b><b>{teamName(context,"team_b")} {pct(context.prediction.team_b_probability)}</b></>:<b>ML prediction unavailable</b>}</div><dl><div><dt>Надёжность анализа</dt><dd>{confidenceLabels[analysis.conclusion.confidence]}</dd></div><div><dt>Качество данных</dt><dd>{qualityLabels[context.data_quality.overall_status]}</dd></div></dl></div>
      <div className={`llm-summary ${analysis.analysis_status==="insufficient_data"?"llm-summary--insufficient":""}`}><p className="eyebrow">Краткий вывод</p><h3>{analysis.analysis_status==="insufficient_data"?"Недостаточно данных для надёжного анализа.":analysis.summary}</h3>{analysis.analysis_status==="insufficient_data"&&analysis.summary&&<p>{analysis.summary}</p>}</div>
      <div className="llm-columns">{analysis.key_advantages.length>0&&<section><h3>Почему фаворит имеет преимущество</h3>{analysis.key_advantages.map(claim=><ClaimCard key={claim.claim_id} claim={claim} context={context} kind="claim"/>)}</section>}{analysis.counter_arguments.length>0&&<section><h3>Что играет против фаворита</h3>{analysis.counter_arguments.map(claim=><ClaimCard key={claim.claim_id} claim={claim} context={context} kind="claim"/>)}</section>}</div>
      {analysis.contradictions.length>0&&<section className="llm-contradictions"><h3>Противоречия в данных</h3>{analysis.contradictions.map(item=><article key={item.contradiction_id}><span>↔</span><p>{item.description}</p></article>)}</section>}
      <div className="llm-columns">{analysis.risks.length>0&&<section><h3>Риски прогноза</h3>{analysis.risks.map(item=><ClaimCard key={item.risk_id} claim={item} context={context} kind="risk"/>)}</section>}{analysis.data_limitations.length>0&&<section><h3>Ограничения данных</h3>{analysis.data_limitations.map(item=><ClaimCard key={item.limitation_id} claim={item} context={context} kind="limitation"/>)}</section>}</div>
      {(context.data_quality.missing_sections.length>0||context.data_quality.warnings.length>0)&&<details className="llm-quality"><summary>Подробнее о качестве данных</summary>{context.data_quality.missing_sections.length>0&&<p>Отсутствуют разделы: {context.data_quality.missing_sections.join(", ")}</p>}{context.data_quality.warnings.map(item=><p key={item}>{item}</p>)}</details>}
      <footer className="llm-footer"><span>Сгенерировано: {dateTime(run.created_at)}</span><span>Model: {run.runtime.model}</span><span>Prompt: {run.runtime.prompt_version.replace("match_analysis_prompt.","")}</span>{historical&&<button type="button" className="button" disabled={generating} onClick={()=>void regenerate()}>Перегенерировать на тех же данных</button>}<details><summary>Техническая информация</summary><p>Provider: {run.runtime.provider} · attempts: {run.runtime.attempts} · tokens: {run.runtime.input_tokens??"—"}/{run.runtime.output_tokens??"—"}</p><p>Проверки: schema {String(run.runtime.schema_valid)}, business {String(run.runtime.business_valid)}, grounding {String(run.runtime.grounding_valid)}</p></details></footer>
    </>}
  </section>;
}
