import { FormEvent, useEffect, useState } from "react";
import { createTournament, getTeams, importTournamentTeam } from "../api";
import type { Team, TournamentStructure } from "../types";
const structures:Record<TournamentStructure,string>={single_elimination:"Single Elimination",double_elimination:"Double Elimination",swiss:"Swiss",groups:"Groups",groups_playoff:"Groups + Playoff",mixed:"Mixed",unknown:"Unknown"};
export function AddTournamentPage(){
 const [teams,setTeams]=useState<Team[]>([]),[teamIds,setTeamIds]=useState<number[]>([]);const [bo3,setBo3]=useState(""),[error,setError]=useState(""),[busy,setBusy]=useState(false);const [form,setForm]=useState({name:"",year:new Date().getFullYear(),tier:"S",environment:"lan" as "lan"|"online",start_date:"",end_date:"",structure_type:"single_elimination" as TournamentStructure});
 const reload=async()=>setTeams((await getTeams()).sort((a,b)=>Number(b.is_analytics_active)-Number(a.is_analytics_active)||(a.current_rank??9999)-(b.current_rank??9999)));useEffect(()=>{void reload()},[]);
 async function importTeam(){try{setBusy(true);const t=await importTournamentTeam(bo3);await reload();setTeamIds(x=>x.includes(t.id)?x:[...x,t.id]);setBo3("")}catch(x){setError(x instanceof Error?x.message:"Ошибка импорта")}finally{setBusy(false)}}
 async function save(e:FormEvent){e.preventDefault();try{setBusy(true);const t=await createTournament({...form,tier:form.tier||null,team_ids:teamIds,matches:[]});window.location.href=`/tournaments/${t.id}`}catch(x){setError(x instanceof Error?x.message:"Ошибка сохранения");setBusy(false)}}
 return <main className="page tournaments-page"><nav className="page-links"><a href="/tournaments">← Турниры</a><strong>Добавить турнир</strong></nav><h1>Новый турнир</h1><p className="lead">Сначала создайте турнир и выберите участников. Серии добавляются отдельно на странице турнира.</p><form className="match-editor" onSubmit={save}><div className="drawer-grid"><label>Название<input required value={form.name} onChange={e=>setForm({...form,name:e.target.value})}/></label><label>Год<input type="number" value={form.year} onChange={e=>setForm({...form,year:+e.target.value})}/></label><label>Начало<input required type="date" value={form.start_date} onChange={e=>setForm({...form,start_date:e.target.value})}/></label><label>Окончание<input required type="date" value={form.end_date} onChange={e=>setForm({...form,end_date:e.target.value})}/></label><label>Tier<input value={form.tier} onChange={e=>setForm({...form,tier:e.target.value})}/></label><label>LAN / Online<select value={form.environment} onChange={e=>setForm({...form,environment:e.target.value as "lan"|"online"})}><option value="lan">LAN</option><option value="online">Online</option></select></label><label>Структура<select value={form.structure_type} onChange={e=>setForm({...form,structure_type:e.target.value as TournamentStructure})}>{Object.entries(structures).filter(([x])=>x!=="unknown").map(([x,l])=><option value={x} key={x}>{l}</option>)}</select></label></div><h2>Участники</h2><div className="drawer-grid">{teams.map(t=><label key={t.id}><input type="checkbox" checked={teamIds.includes(t.id)} onChange={e=>setTeamIds(e.target.checked?[...teamIds,t.id]:teamIds.filter(x=>x!==t.id))}/>{t.current_rank?`#${t.current_rank} · `:""}{t.name}{!t.is_analytics_active?" · вне Top-30":""}</label>)}</div><div className="drawer-grid"><label>BO3 slug/URL<input value={bo3} onChange={e=>setBo3(e.target.value)}/></label><button type="button" className="button" disabled={!bo3||busy} onClick={()=>void importTeam()}>+ Добавить команду</button></div>{error&&<div className="empty-state empty-state--error">{error}</div>}<button className="button button--primary" disabled={busy||!teamIds.length}>{busy?"Сохраняю…":"Создать турнир"}</button></form></main>;
}
