import {useEffect,useMemo,useState} from "react";
import {backtestSandboxMatchup,getLatestMLFeatureDiagnostics,getModelSandbox,previewSandboxMatchup,trainSandboxML} from "../api";

declare global {interface ObjectConstructor {groupBy<T>(items:T[],key:(item:T)=>PropertyKey):Record<PropertyKey,T[]>}}
if(!Object.groupBy)Object.groupBy=function<T>(items:T[],key:(item:T)=>PropertyKey){return items.reduce((out,item)=>{const group=key(item);(out[group]??=[]).push(item);return out},{} as Record<PropertyKey,T[]>)};

const pct=(x:number|null|undefined)=>x==null?"—":`${(x*100).toFixed(1)}%`;
const num=(x:number|null|undefined,d=2)=>x==null?"—":x.toFixed(d);
type Factor={label:string;hint:string;weight:number;min_reliability:number;max_effect:number;reliability_mode:string};

export function ModelSandboxPage(){
 const [data,setData]=useState<any>(null),[tab,setTab]=useState<"matchup"|"ml">("matchup"),[config,setConfig]=useState<any>(null),[matchId,setMatchId]=useState<number>(0),[preview,setPreview]=useState<any>(null),[backtest,setBacktest]=useState<any>(null),[enabled,setEnabled]=useState<string[]>([]),[diagnostics,setDiagnostics]=useState<any>(null),[mlResult,setMlResult]=useState<any>(null),[busy,setBusy]=useState(""),[error,setError]=useState("");
 useEffect(()=>{getModelSandbox().then(async value=>{setData(value);setConfig(structuredClone(value.production_config));setMatchId(value.matches[0]?.id||0);setEnabled(value.ml.features.map((x:any)=>x.key));try{setDiagnostics(await getLatestMLFeatureDiagnostics())}catch{/* optional */}}).catch(e=>setError(e.message))},[]);
 useEffect(()=>{if(!matchId||!config)return;const timer=setTimeout(()=>{setBusy("preview");previewSandboxMatchup(matchId,config).then(setPreview).catch(e=>setError(e.message)).finally(()=>setBusy(""))},250);return()=>clearTimeout(timer)},[matchId,config]);
 const rawSum=useMemo(()=>config?Object.values(config.factors as Record<string,Factor>).reduce((a,x)=>a+x.weight,0):0,[config]);
 const update=(key:string,field:keyof Factor,value:string)=>setConfig((old:any)=>({...old,factors:{...old.factors,[key]:{...old.factors[key],[field]:field==="reliability_mode"?value:Number(value)}}}));
 const reset=()=>{setConfig(structuredClone(data.production_config));setBacktest(null)};
 const save=()=>{const name=prompt("Название sandbox preset");if(name){const all=JSON.parse(localStorage.getItem("matchup_sandbox_presets")||"{}");all[name]=config;localStorage.setItem("matchup_sandbox_presets",JSON.stringify(all))}};
 const load=()=>{const all=JSON.parse(localStorage.getItem("matchup_sandbox_presets")||"{}");const name=prompt(`Preset: ${Object.keys(all).join(", ")}`);if(name&&all[name])setConfig(all[name])};
 const remove=()=>{const all=JSON.parse(localStorage.getItem("matchup_sandbox_presets")||"{}");const name=prompt(`Удалить: ${Object.keys(all).join(", ")}`);if(name){delete all[name];localStorage.setItem("matchup_sandbox_presets",JSON.stringify(all))}};
 if(!data||!config)return <main className="page"><div className="empty-state">{error||"Загружаю Model Sandbox…"}</div></main>;
 return <main className="page sandbox"><nav className="page-links"><a className="back-link" href="/">← На главную</a><a href="/ml/feature-diagnostics">Диагностика текущей ML-модели →</a><a href="/matchup-calibration">Фиксированная Matchup calibration →</a></nav><header className="section-heading"><div><p className="eyebrow">Эксперименты без изменения production</p><h1>Model Sandbox — ручные эксперименты</h1><p>Здесь меняют Matchup-настройки или набор ML-признаков и проверяют временный candidate. Production, Prediction History и official predictions не изменяются.</p></div></header>
 <div className="sandbox-tabs"><button className={tab==="matchup"?"button button--primary":"button"} onClick={()=>setTab("matchup")}>Matchup: изменить формулу</button><button className={tab==="ml"?"button button--primary":"button"} onClick={()=>setTab("ml")}>ML: обучить candidate</button></div>{error&&<div className="empty-state empty-state--error">{error}</div>}
 {tab==="matchup"?<><section className="team-card sandbox-toolbar"><label>Матч <select value={matchId} onChange={e=>setMatchId(Number(e.target.value))}>{data.matches.map((x:any)=><option key={x.id} value={x.id}>#{x.id} · {x.team_a_id} vs {x.team_b_id} · {x.match_date}</option>)}</select></label><label>Preset <select onChange={e=>{if(e.target.value==="production")reset()}}><option value="custom">Custom</option><option value="production">Production</option></select></label><button className="button" onClick={reset}>Сбросить к production</button><button className="button" onClick={save}>Сохранить preset</button><button className="button" onClick={load}>Загрузить preset</button><button className="button" onClick={remove}>Удалить preset</button></section>
 <div className="sandbox-grid"><section className="strength-panel"><div className="section-heading"><div><h2>Факторы</h2><p className={Math.abs(rawSum-1)>.0001?"sandbox-warning":""}>Сумма весов = {(rawSum*100).toFixed(1)}%.</p></div><label><input type="checkbox" checked={config.normalize_weights} onChange={e=>setConfig({...config,normalize_weights:e.target.checked})}/> Нормализовать веса до 100% при расчёте</label></div>{Object.entries(config.factors as Record<string,Factor>).map(([key,f])=><article className="sandbox-factor" key={key}><h3>{f.label}</h3><p>{f.hint}</p><small>Production вес: {pct(data.production_config.factors[key].weight)} · Effective: {pct(preview?.config_meta?.effective_weights?.[key]??f.weight)}</small><Control label="Weight" value={f.weight} min={0} max={.5} step={.01} display={pct(f.weight)} onChange={v=>update(key,"weight",v)}/><Control label="Min reliability" value={f.min_reliability} min={0} max={1} step={.05} display={pct(f.min_reliability)} onChange={v=>update(key,"min_reliability",v)}/><Control label="Max effect" value={f.max_effect} min={0} max={10} step={.1} display={num(f.max_effect,1)} onChange={v=>update(key,"max_effect",v)}/><label>Reliability mode <select value={f.reliability_mode} onChange={e=>update(key,"reliability_mode",e.target.value)}><option value="linear">Linear</option><option value="conservative">Conservative</option><option value="thresholded">Threshold</option><option value="none">None</option><option value="gated">Gated</option></select></label></article>)}</section>
 <aside><Result title="PRODUCTION" value={preview?.production}/><Result title="SANDBOX" value={preview?.sandbox}/>{preview?.winner_changed&&<div className="empty-state sandbox-flip"><b>Winner changed</b><br/>{preview.production_winner_id??"neutral"} → {preview.sandbox_winner_id??"neutral"}</div>}</aside></div>
 {preview&&<section className="strength-panel"><h2>Factor contribution comparison</h2><div className="table-wrap"><table><thead><tr><th>Factor</th><th>Score</th><th>Reliability</th><th>Raw</th><th>Production</th><th>Sandbox</th></tr></thead><tbody>{preview.factor_comparison.map((x:any)=><tr key={x.key}><td>{x.label}</td><td>{num(x.score)}</td><td>{pct(x.reliability)}</td><td>{num(x.raw_contribution)}</td><td>{num(x.production_contribution)}</td><td>{num(x.sandbox_contribution)}</td></tr>)}</tbody></table></div></section>}
 <button className="button button--primary" disabled={!!busy} onClick={()=>{setBusy("backtest");backtestSandboxMatchup(config).then(setBacktest).catch(e=>setError(e.message)).finally(()=>setBusy(""))}}>{busy==="backtest"?"Считаю…":"Проверить на истории"}</button>{backtest&&<Backtest value={backtest}/>}</>:<MLTab data={data} enabled={enabled} setEnabled={setEnabled} diagnostics={diagnostics} result={mlResult} busy={busy} train={()=>{setBusy("ml");trainSandboxML(enabled).then(setMlResult).catch(e=>setError(e.message)).finally(()=>setBusy(""))}} reset={()=>setEnabled(data.ml.features.map((x:any)=>x.key))}/>}</main>
}
function Control(p:{label:string;value:number;min:number;max:number;step:number;display:string;onChange:(v:string)=>void}){return <label className="sandbox-control"><span>{p.label}</span><input aria-label={`${p.label} slider`} type="range" value={p.value} min={p.min} max={p.max} step={p.step} onChange={e=>p.onChange(e.target.value)}/><input aria-label={`${p.label} numeric`} type="number" value={p.value} min={p.min} max={p.max} step={p.step} onChange={e=>p.onChange(e.target.value)}/><b>{p.display}</b></label>}
function Result({title,value}:{title:string;value:any}){return <article className="team-card"><p className="eyebrow">{title}</p>{value?<><h2>{value.team_a.name||value.team_a.id} {value.team_a.score}</h2><h2>{value.team_b.name||value.team_b.id} {value.team_b.score}</h2></>:<p>Выберите матч</p>}</article>}
function Backtest({value:v}:{value:any}){return <section className="strength-panel"><h2>Backtest report</h2><div className="team-grid"><ResultMetric title="Production" x={v.baseline}/><ResultMetric title="Sandbox" x={v.candidate}/></div><h3>Delta: {v.delta.accuracy==null?"—":`${v.delta.accuracy>=0?"+":""}${(v.delta.accuracy*100).toFixed(1)} pp`}</h3><p>Predictions changed: {v.flips.total} · Fixed production errors: {v.flips.v2_fixed_v1_error} · Broke production correct: {v.flips.v2_broke_v1_correct} · Net: {v.flips.net_improvement>=0?"+":""}{v.flips.net_improvement}</p><div className="table-wrap"><table><thead><tr><th>Match</th><th>Production winner</th><th>Sandbox winner</th><th>Actual</th><th>Result</th></tr></thead><tbody>{v.flips.matches.map((x:any)=><tr key={x.match_id}><td><a href={`/matches/${x.match_id}`}>{x.match}</a></td><td>{x.baseline_winner_id}</td><td>{x.candidate_winner_id}</td><td>{x.actual_winner_id}</td><td><b>{x.result.toUpperCase()}</b></td></tr>)}</tbody></table></div><h3>Average absolute contribution</h3>{Object.entries(v.factor_impact_comparison).map(([key,x]:any)=><p key={key}>{key}: Production {num(x.baseline_average_absolute_contribution)} · Sandbox {num(x.candidate_average_absolute_contribution)}</p>)}</section>}
function ResultMetric({title,x}:{title:string;x:any}){return <article className="team-card"><h3>{title}</h3><p>Matches: {x.matches}</p><p>Accuracy: {pct(x.accuracy)}</p>{Object.entries(x.margin_buckets||{}).map(([k,b]:any)=><small key={k}>{k}: {pct(b.accuracy)} ({b.samples}) · </small>)}</article>}
function MLTab({data,enabled,setEnabled,diagnostics,result,busy,train,reset}:any){const status=Object.fromEntries((diagnostics?.features||[]).map((x:any)=>[x.feature,x.diagnostic_status]));const groups=Object.entries(Object.groupBy(data.ml.features,(x:any)=>x.group));return <><section className="team-card"><p>Current: <b>{data.ml.current_schema||"No active model"}</b></p><p>Candidate: <b>custom_sandbox</b> · {enabled.length} / {data.ml.features.length} features enabled</p><button className="button" onClick={reset}>Вернуть current feature schema</button></section>{groups.map(([group,items]:any)=><section className="strength-panel" key={group}><h2>{group}</h2>{items.map((x:any)=><label className="sandbox-feature" key={x.key}><input type="checkbox" checked={enabled.includes(x.key)} onChange={()=>setEnabled((old:string[])=>old.includes(x.key)?old.filter(k=>k!==x.key):[...old,x.key])}/><strong>{x.key}</strong><span className="source-badge">{status[x.key]||"NO DIAGNOSTIC"}</span></label>)}</section>)}<button className="button button--primary" disabled={!!busy||!enabled.length} onClick={train}>{busy==="ml"?"Обучаю temporal candidate…":"Обучить candidate"}</button>{result&&<section className="team-card"><h2>Candidate #{result.candidate_id} · {result.status.toUpperCase()}</h2><p>Active: NO · Gate preview: <b>{result.gate_preview}</b></p><p>Current ML — Brier {num(result.quality.current?.brier_score,4)}, LogLoss {num(result.quality.current?.log_loss,4)}, Accuracy {pct(result.quality.current?.accuracy)}</p><p>Sandbox ML — Brier {num(result.quality.sandbox.brier_score,4)}, LogLoss {num(result.quality.sandbox.log_loss,4)}, Accuracy {pct(result.quality.sandbox.accuracy)}</p><p>Unexpected coefficients: {result.diagnostics.features.filter((x:any)=>x.sign_mismatch).length} · Unstable features: {result.diagnostics.features.filter((x:any)=>x.stability_status==="unstable").length} · Very-high correlation pairs: {result.diagnostics.redundancy_candidates.filter((x:any)=>x.level==="very_high").length}</p></section>}</>}
