import {useEffect,useState} from "react";
import {getPredictionHistory} from "../api";
import type {PredictionConflictMetric,PredictionConflictType,PredictionHistoryItem,PredictionHistoryMetric,PredictionHistoryPrediction,PredictionHistoryResponse} from "../types";

const metric=(label:string,value:PredictionHistoryMetric)=><article><span>{label}</span><strong>{value.correct} / {value.total}</strong><b>{value.accuracy===null?"—":`${Math.round(value.accuracy*100)}%`}</b></article>;
const mark=(correct:boolean|null)=>correct===null?"⏳":correct?"✅":"❌";
const prediction=(value:PredictionHistoryPrediction)=>value.predicted_winner?`${mark(value.correct)} ${value.predicted_winner}${value.probability&&value.team_a_value!==null&&value.team_b_value!==null?` ${Math.round(Math.max(value.team_a_value,value.team_b_value)*100)}%`:""}`:"—";
const conflictLabels:Record<PredictionConflictType,string>={none:"3/3 — конфликта нет",incomplete:"Incomplete",ts_matchup_vs_ml:"TS + Matchup vs ML",ts_ml_vs_matchup:"TS + ML vs Matchup",matchup_ml_vs_ts:"Matchup + ML vs TS",all_three_different:"Все три разные"};
const conflictStat=(label:string,value:PredictionConflictMetric,dissentLabel:string,majorityLabel:string)=><article><strong>{label}</strong><span>Завершённых: {value.total}</span><small>{dissentLabel}: {value.dissent_correct} — {value.dissent_accuracy===null?"—":`${Math.round(value.dissent_accuracy*100)}%`}</small><small>{majorityLabel}: {value.majority_correct} — {value.majority_accuracy===null?"—":`${Math.round(value.majority_accuracy*100)}%`}</small></article>;
const rawValues=(item:PredictionHistoryItem,value:PredictionHistoryPrediction)=>value.team_a_value===null||value.team_b_value===null?null:<small>{item.team_a.name} {value.probability?`${Math.round(value.team_a_value*100)}%`:value.team_a_value.toFixed(1)} / {item.team_b.name} {value.probability?`${Math.round(value.team_b_value*100)}%`:value.team_b_value.toFixed(1)}</small>;

export function PredictionHistoryPage(){
 const [data,setData]=useState<PredictionHistoryResponse|null>(null),[error,setError]=useState<string|null>(null),[loading,setLoading]=useState(true);
 const [tournamentId,setTournamentId]=useState(0),[date,setDate]=useState(""),[status,setStatus]=useState<""|"completed"|"future">(""),[consensus,setConsensus]=useState(false),[conflictOnly,setConflictOnly]=useState(false),[conflictStrength,setConflictStrength]=useState<"all"|"strong">("all");
 useEffect(()=>{setLoading(true);setError(null);getPredictionHistory({tournamentId:tournamentId||undefined,date:date||undefined,status:status||undefined,consensus,conflictOnly,strongConflicts:conflictStrength==="strong"}).then(setData).catch(x=>setError(x instanceof Error?x.message:"Не удалось загрузить историю.")).finally(()=>setLoading(false))},[tournamentId,date,status,consensus,conflictOnly,conflictStrength]);
 return <main className="page prediction-history"><nav className="page-links"><a className="back-link" href="/">← К командам</a><strong>CS2Eye · Prediction History</strong></nav><header className="compare-heading"><p className="eyebrow">Immutable pre-match snapshots</p><h1>Prediction History</h1><p className="lead">Предматчевые прогнозы в исходном виде и их фактический результат.</p></header>
 {data&&<section className="prediction-history__stats">{metric("Team Strength",data.statistics.team_strength)}{metric("Matchup Score",data.statistics.matchup)}{metric("ML Prediction",data.statistics.ml)}{metric("3/3 Consensus",data.statistics.consensus_3_3)}</section>}
 {data&&<section className="prediction-conflict__stats">{conflictStat("TS + Matchup vs ML",data.statistics.conflicts.ts_matchup_vs_ml,"ML права","TS + Matchup правы")}{conflictStat("TS + ML vs Matchup",data.statistics.conflicts.ts_ml_vs_matchup,"Matchup прав","TS + ML правы")}{conflictStat("Matchup + ML vs TS",data.statistics.conflicts.matchup_ml_vs_ts,"TS права","Matchup + ML правы")}</section>}
 <section className="prediction-history__filters"><label>Турнир<select value={tournamentId} onChange={e=>setTournamentId(+e.target.value)}><option value={0}>Все</option>{data?.tournaments.map(x=><option key={x.id} value={x.id}>{x.name}</option>)}</select></label><label>Дата<input type="date" value={date} onChange={e=>setDate(e.target.value)}/></label><label>Статус<select value={status} onChange={e=>setStatus(e.target.value as typeof status)}><option value="">Все</option><option value="completed">Завершённые</option><option value="future">Будущие</option></select></label><label><input type="checkbox" checked={consensus} onChange={e=>setConsensus(e.target.checked)}/> Только 3/3 consensus</label><label><input type="checkbox" checked={conflictOnly} onChange={e=>setConflictOnly(e.target.checked)}/> Только расхождения</label><label>Сила конфликта<select value={conflictStrength} onChange={e=>setConflictStrength(e.target.value as typeof conflictStrength)}><option value="all">Все конфликты</option><option value="strong">Сильные конфликты</option></select></label></section>
 {error&&<div className="empty-state empty-state--error">{error}</div>}{loading?<div className="empty-state">Загружаю историю…</div>:!data?.items.length?<div className="empty-state">Snapshot-прогнозов по выбранным фильтрам нет.</div>:<div className="prediction-history__table prediction-history__table--conflicts"><div className="head"><span>Матч</span><span>Факт</span><span>Team Strength</span><span>Matchup</span><span>ML</span><span>Consensus</span><span>Conflict</span></div>{data.items.map(x=><div key={x.id}><span><a href={`/matches/${x.match_id}`}>{x.team_a.name} vs {x.team_b.name}</a><small>{x.tournament} · {new Date(`${x.match_date}T00:00:00Z`).toLocaleDateString("ru-RU")} · {x.source==="live"?"live snapshot":"ретроспективно"}</small></span><span>{x.actual_winner??"—"}</span><span>{prediction(x.team_strength)}{x.conflict.type!=="none"&&rawValues(x,x.team_strength)}</span><span>{prediction(x.matchup)}{x.conflict.type!=="none"&&rawValues(x,x.matchup)}</span><span>{prediction(x.ml)}{x.conflict.type!=="none"&&rawValues(x,x.ml)}</span><span>{x.consensus.winner?`${mark(x.consensus.correct)} ${x.consensus.votes}/3 ${x.consensus.winner}`:"—"}</span><span><b>{conflictLabels[x.conflict.type]}</b>{x.conflict.strength!==null&&x.conflict.type!=="none"&&<small>Сила: {x.conflict.strength.toFixed(1)}{x.conflict.strong?" · сильный":""}</small>}</span></div>)}</div>}</main>
}
