import {useEffect,useState} from "react";
import type {ReactNode} from "react";
import {getPredictionHistory} from "../api";
import type {PredictionComparisonType,PredictionHistoryItem,PredictionHistoryMetric,PredictionHistoryPrediction,PredictionHistoryResponse} from "../types";

const percent=(value:number|null|undefined,digits=1)=>value==null?"—":`${(value*100).toFixed(digits)}%`;
const metric=(label:string,value:PredictionHistoryMetric,extra?:ReactNode)=><article><span>{label}</span><strong>{value.correct} / {value.total}</strong><b>Accuracy: {percent(value.accuracy)}</b>{extra}</article>;
const mark=(correct:boolean|null)=>correct===null?"⏳":correct?"✅":"❌";
const prediction=(value:PredictionHistoryPrediction)=>value.evaluation_status==="not_evaluable_retrospective"?"N/A · retrospective · не оценивается":value.predicted_winner?`${mark(value.correct)} ${value.predicted_winner}${value.probability&&value.team_a_value!==null&&value.team_b_value!==null?` ${Math.round(Math.max(value.team_a_value,value.team_b_value)*100)}%`:""}`:"—";
const comparisonLabels:Record<PredictionComparisonType,string>={consensus_3_3:"3/3 consensus",team_strength_dissent:"Team Strength dissent",matchup_dissent:"Matchup dissent",ml_dissent:"ML dissent",incomplete:"Неполные"};
const rawValues=(item:PredictionHistoryItem,value:PredictionHistoryPrediction)=>value.team_a_value===null||value.team_b_value===null?null:<small>{item.team_a.name} {value.probability?`${Math.round(value.team_a_value*100)}%`:value.team_a_value.toFixed(1)} / {item.team_b.name} {value.probability?`${Math.round(value.team_b_value*100)}%`:value.team_b_value.toFixed(1)}</small>;

function ErrorDetail({item}:{item:PredictionHistoryItem}){
 const analysis=item.error_analysis;
 if(!analysis)return <div className="prediction-error-detail"><p>Error analysis недоступен для legacy snapshot.</p></div>;
 const matchup=analysis.matchup;
 return <div className="prediction-error-detail"><div><strong>Результат: {item.actual_winner??"ещё неизвестен"}</strong><p>Team Strength: margin {analysis.team_strength.margin?.toFixed(1)??"—"} · {mark(analysis.team_strength.is_correct)}</p><p>Matchup: margin {matchup.margin?.toFixed(1)??"—"} · {mark(matchup.is_correct)}</p><p>ML: {analysis.ml.probability==null?"—":percent(analysis.ml.probability)} · {mark(analysis.ml.is_correct)}</p></div>{matchup.status==="not_available"?<p>Matchup factor analysis: not_available — legacy snapshot без сохранённых факторов.</p>:<div><h3>Факторы Matchup</h3>{matchup.is_correct===false&&matchup.error_drivers[0]&&<p className="prediction-error-driver"><strong>Главный фактор ошибки модели: {matchup.error_drivers[0].label}</strong><br/>{matchup.error_drivers[0].label} дал {matchup.error_drivers[0].contribution.toFixed(2)} балла в сторону ошибочно выбранной команды. Это объясняет решение модели, а не причину результата матча.</p>}<table><thead><tr><th>Фактор</th><th>Вклад</th><th>Направление</th><th>Reliability</th></tr></thead><tbody>{matchup.factors.map(f=>{const side=f.contribution>0?item.team_a.name:f.contribution<0?item.team_b.name:"neutral";return <tr key={f.factor} className={matchup.error_drivers[0]?.factor===f.factor?"is-top-driver":""}><td>{f.label}</td><td>{f.contribution>0?"+":""}{f.contribution.toFixed(2)}</td><td>{side} {f.direction_correct==null?"neutral":mark(f.direction_correct)}</td><td>{f.reliability==null?"—":percent(f.reliability)}</td></tr>})}</tbody></table></div>}</div>;
}

export function PredictionHistoryPage(){
 const [data,setData]=useState<PredictionHistoryResponse|null>(null),[error,setError]=useState<string|null>(null),[loading,setLoading]=useState(true),[expanded,setExpanded]=useState<number|null>(null);
 const [tournamentId,setTournamentId]=useState(0),[date,setDate]=useState(""),[status,setStatus]=useState<""|"completed"|"future">(""),[source,setSource]=useState<""|"pre_match"|"retrospective">("");
 const [comparisonType,setComparisonType]=useState<""|PredictionComparisonType>(""),[mlVersion,setMlVersion]=useState(""),[matchupVersion,setMatchupVersion]=useState("");
 const [errorResult,setErrorResult]=useState(""),[errorDriver,setErrorDriver]=useState(""),[mlError,setMlError]=useState(0);
 useEffect(()=>{setLoading(true);setError(null);getPredictionHistory({tournamentId:tournamentId||undefined,date:date||undefined,status:status||undefined,source:source||undefined,comparisonType:comparisonType||undefined,mlModelVersion:mlVersion||undefined,matchupModelVersion:matchupVersion||undefined,errorResult:errorResult||undefined,matchupErrorDriver:errorDriver||undefined,mlConfidenceError:mlError||undefined}).then(setData).catch(x=>setError(x instanceof Error?x.message:"Не удалось загрузить историю.")).finally(()=>setLoading(false))},[tournamentId,date,status,source,comparisonType,mlVersion,matchupVersion,errorResult,errorDriver,mlError]);
 const stats=data?.statistics, conflicts=stats?.conflicts, dissent=stats?.dissent, quality=stats?.ml_quality;
 const factorKeys=Object.keys(stats?.matchup_factor_quality??{});
 return <main className="page prediction-history"><nav className="page-links"><a className="back-link" href="/">← К командам</a><strong>CS2Eye · Prediction History</strong></nav><header className="compare-heading"><p className="eyebrow">Immutable pre-match snapshots</p><h1>Prediction History</h1><p className="lead">Детерминированная диагностика решений Team Strength, Matchup Score и ML.</p></header>
 {stats&&<><aside className="prediction-history__integrity"><strong>Official metrics: только completed pre-match snapshot с известным победителем.</strong><span>Завершённых pre-match snapshot: {stats.snapshot_counts.completed_pre_match}</span><small>Всего: pre-match — {stats.snapshot_counts.pre_match}, retrospective — {stats.snapshot_counts.retrospective}</small></aside><section className="prediction-history__stats">{metric("Team Strength",stats.team_strength)}{metric("Matchup Score",stats.matchup)}{metric("ML",stats.ml,<><small>Brier: {quality?.brier_score?.toFixed(3)??"—"}</small><small>Log Loss: {quality?.log_loss?.toFixed(3)??"—"}</small></>)}{metric("3/3 consensus",stats.consensus_3_3)}</section></>}
 {stats&&<section className="prediction-conflict__stats"><article><strong>Majority 2/3</strong><span>{conflicts?.majority_correct??0} / {conflicts?.total??0}</span><b>{percent(conflicts?.majority_accuracy)}</b></article><article><strong>Dissent</strong><span>{conflicts?.dissent_correct??0} / {conflicts?.total??0}</span><b>{percent(conflicts?.dissent_accuracy)}</b></article>{(["team_strength","matchup","ml"] as const).map(model=><article key={model}><strong>Когда dissent = {model==="team_strength"?"Team Strength":model==="matchup"?"Matchup":"ML"}</strong><span>{dissent?.[model]?.dissent_correct??0} / {dissent?.[model]?.cases??0}</span><b>{percent(dissent?.[model]?.dissent_accuracy)}</b></article>)}</section>}
 {stats?.matchup_factor_quality&&<section className="prediction-calibration"><h2>Matchup factor quality</h2><table><thead><tr><th>Factor</th><th>Direction accuracy</th><th>Cases</th><th>Top error driver</th></tr></thead><tbody>{Object.entries(stats.matchup_factor_quality).map(([key,value])=><tr key={key}><td>{value.label}</td><td>{percent(value.direction_accuracy)}</td><td>n={value.directional_cases}</td><td>{stats.matchup_error_drivers?.[key]?.top_driver_cases??0}</td></tr>)}</tbody></table></section>}
 {stats?.ml_high_confidence_errors&&<section className="prediction-calibration"><h2>ML high-confidence errors</h2><table><thead><tr><th>Threshold</th><th>Predictions</th><th>Errors</th><th>Error rate</th></tr></thead><tbody>{Object.entries(stats.ml_high_confidence_errors).map(([key,value])=><tr key={key}><td>{key.replace("_plus","%+")}</td><td>{value.predictions}</td><td>{value.errors}</td><td>{percent(value.error_rate)}</td></tr>)}</tbody></table></section>}
 <section className="prediction-history__filters"><label>Турнир<select value={tournamentId} onChange={e=>setTournamentId(+e.target.value)}><option value={0}>Все</option>{data?.tournaments.map(x=><option key={x.id} value={x.id}>{x.name}</option>)}</select></label><label>Дата<input type="date" value={date} onChange={e=>setDate(e.target.value)}/></label><label>Статус<select value={status} onChange={e=>setStatus(e.target.value as typeof status)}><option value="">Все</option><option value="completed">Завершённые</option><option value="future">Будущие</option></select></label><label>Источник<select value={source} onChange={e=>setSource(e.target.value as typeof source)}><option value="">Все</option><option value="pre_match">Pre-match</option><option value="retrospective">Retrospective</option></select></label><label>ML version<select value={mlVersion} onChange={e=>setMlVersion(e.target.value)}><option value="">Все</option>{data?.model_versions?.ml.map(x=><option value={x} key={x}>{x}</option>)}</select></label><label>Matchup version<select value={matchupVersion} onChange={e=>setMatchupVersion(e.target.value)}><option value="">Все</option>{data?.model_versions?.matchup.map(x=><option value={x} key={x}>{x}</option>)}</select></label><label>Согласие<select value={comparisonType} onChange={e=>setComparisonType(e.target.value as typeof comparisonType)}><option value="">Все</option><option value="consensus_3_3">3/3</option><option value="team_strength_dissent">TS против двух</option><option value="matchup_dissent">Matchup против двух</option><option value="ml_dissent">ML против двух</option><option value="incomplete">Неполные</option></select></label><label>Результат предикта<select value={errorResult} onChange={e=>setErrorResult(e.target.value)}><option value="">Все</option><option value="any">Любая модель ошиблась</option><option value="matchup">Matchup ошибся</option><option value="team_strength">Team Strength ошибся</option><option value="ml">ML ошибся</option></select></label><label>Главный фактор ошибки<select value={errorDriver} onChange={e=>setErrorDriver(e.target.value)}><option value="">Все</option>{factorKeys.map(key=><option value={key} key={key}>{stats?.matchup_factor_quality?.[key].label??key}</option>)}</select></label><label>ML ошибки<select value={mlError} onChange={e=>setMlError(+e.target.value)}><option value={0}>Все</option><option value={60}>Ошибки 60%+</option><option value={70}>Ошибки 70%+</option><option value={80}>Ошибки 80%+</option></select></label></section>
 {stats?.calibration&&<section className="prediction-calibration"><h2>ML calibration</h2><table><thead><tr><th>ML probability</th><th>Matches</th><th>Avg prediction</th><th>Actual wins</th></tr></thead><tbody>{stats.calibration.map(x=><tr key={x.range}><td>{x.range.replace("-","–")}%</td><td>n={x.samples}</td><td>{percent(x.average_predicted_probability)}</td><td>{percent(x.actual_win_rate)}</td></tr>)}</tbody></table></section>}
 {error&&<div className="empty-state empty-state--error">{error}</div>}{loading?<div className="empty-state">Загружаю историю…</div>:!data?.items.length?<div className="empty-state">Snapshot-прогнозов по выбранным фильтрам нет.</div>:<div className="prediction-history__table prediction-history__table--conflicts"><div className="head"><span>Матч</span><span>Факт</span><span>Team Strength</span><span>Matchup</span><span>ML</span><span>Согласие</span></div>{data.items.map(x=>{const comparison=x.comparison;const dissentCorrect=comparison?.dissent_winner_id!=null&&x.actual_winner_id!=null?comparison.dissent_winner_id===x.actual_winner_id:null;return <section key={x.id} className="prediction-history-entry"><div className={x.evaluation.eligible?"":"prediction-history__row--retrospective"}><span><a href={`/matches/${x.match_id}`}>{x.team_a.name} vs {x.team_b.name}</a><small>{x.tournament} · {new Date(`${x.match_date}T00:00:00Z`).toLocaleDateString("ru-RU")} · {x.source==="pre_match"?"pre-match":"retrospective · не участвует в official metrics"}</small><button className="button" onClick={()=>setExpanded(expanded===x.id?null:x.id)}>{expanded===x.id?"Скрыть разбор":"Разбор ошибки"}</button></span><span>{x.actual_winner??"—"}</span><span>{prediction(x.team_strength)}{rawValues(x,x.team_strength)}</span><span>{prediction(x.matchup)}{rawValues(x,x.matchup)}</span><span>{prediction(x.ml)}{rawValues(x,x.ml)}</span><span><b>{comparison?comparisonLabels[comparison.type]:x.consensus.votes===3?"3/3 consensus":"—"}</b>{comparison?.dissent_model&&<small>{mark(dissentCorrect)} {dissentCorrect?"dissent прав":"большинство право"}</small>}</span></div>{expanded===x.id&&<ErrorDetail item={x}/>}</section>})}</div>}</main>;
}
