import {cleanup,fireEvent,render,screen,waitFor} from "@testing-library/react";
import {afterEach,describe,expect,it,vi} from "vitest";
import type {PredictionHistoryResponse} from "../types";

const api=vi.hoisted(()=>({getPredictionHistory:vi.fn()}));
vi.mock("../api",()=>api);
import {PredictionHistoryPage} from "./PredictionHistoryPage";
afterEach(()=>{cleanup();vi.clearAllMocks()});

const prediction=(winner:"FURIA"|"Legacy",probability=false)=>({team_a_value:probability ? .57 : 60,team_b_value:probability ? .43 : 40,predicted_winner_id:winner==="FURIA"?1:2,predicted_winner:winner,correct:winner==="FURIA",probability,evaluation_status:"available" as const});
const preMatch={id:1,match_id:160,tournament_id:7,tournament:"Test Cup",match_date:"2026-08-30",as_of:"2026-08-29T10:00:00Z",created_at:"2026-08-29T10:00:00Z",source:"pre_match" as const,evaluation:{eligible:true,reason:null},versions:{team_strength:"v2",matchup:"matchup_v1",ml:"ml_v1",ml_feature_schema:"features_v2"},team_a:{id:1,name:"FURIA"},team_b:{id:2,name:"Legacy"},actual_winner_id:1,actual_winner:"FURIA",completed:true,team_strength:prediction("FURIA"),matchup:prediction("Legacy"),ml:prediction("FURIA",true),consensus:{winner_id:1,winner:"FURIA",votes:2,total:3,correct:true},conflict:{type:"ts_ml_vs_matchup" as const,strength:16,strong:true,majority_winner_id:1,majority_winner:"FURIA",dissent_winner_id:2,dissent_winner:"Legacy",dissenting_prediction:"matchup" as const}};
const retrospective={...preMatch,id:2,match_id:161,source:"retrospective" as const,evaluation:{eligible:false,reason:"retrospective" as const},versions:{team_strength:null,matchup:null,ml:null,ml_feature_schema:null},ml:{team_a_value:null,team_b_value:null,predicted_winner_id:null,predicted_winner:null,correct:null,probability:true,evaluation_status:"not_evaluable_retrospective" as const},consensus:{winner_id:null,winner:null,votes:0,total:0,correct:null},conflict:{type:"incomplete" as const,strength:null,strong:false,majority_winner_id:null,majority_winner:null,dissent_winner_id:null,dissent_winner:null,dissenting_prediction:null}};
const response:PredictionHistoryResponse={tournaments:[{id:7,name:"Test Cup"}],statistics:{team_strength:{correct:1,total:1,accuracy:1},matchup:{correct:0,total:1,accuracy:0},ml:{correct:1,total:1,accuracy:1},consensus_3_3:{correct:0,total:0,accuracy:null},snapshot_counts:{pre_match:1,retrospective:1,completed_pre_match:1},strong_conflict_threshold:10,conflicts:{ts_matchup_vs_ml:{total:0,majority_correct:0,dissent_correct:0,majority_accuracy:null,dissent_accuracy:null},ts_ml_vs_matchup:{total:1,majority_correct:1,dissent_correct:0,majority_accuracy:1,dissent_accuracy:0},matchup_ml_vs_ts:{total:0,majority_correct:0,dissent_correct:0,majority_accuracy:null,dissent_accuracy:null}}},items:[preMatch,retrospective]};

describe("Prediction History",()=>{
 it("distinguishes official and retrospective rows and hides retrospective ML",async()=>{api.getPredictionHistory.mockResolvedValue(response);render(<PredictionHistoryPage/>);const links=await screen.findAllByRole("link",{name:"FURIA vs Legacy"});expect(links[0].getAttribute("href")).toBe("/matches/160");expect(screen.getByText("✅ FURIA 57%")).toBeTruthy();expect(screen.getByText(/Official metrics: только completed pre-match/)).toBeTruthy();expect(screen.getByText(/Завершённых pre-match snapshot: 1/)).toBeTruthy();expect(screen.getByText(/retrospective · не участвует в official metrics/)).toBeTruthy();expect(screen.getByText("N/A · retrospective · не оценивается")).toBeTruthy()});
 it("sends comparison and model version filters",async()=>{api.getPredictionHistory.mockResolvedValue({...response,model_versions:{team_strength:["v2"],matchup:["matchup_v1"],ml:["ml_v1"]}});render(<PredictionHistoryPage/>);await screen.findAllByText("FURIA vs Legacy");fireEvent.change(screen.getByLabelText("Турнир"),{target:{value:"7"}});fireEvent.change(screen.getByLabelText("Дата"),{target:{value:"2026-08-30"}});fireEvent.change(screen.getByLabelText("Статус"),{target:{value:"completed"}});fireEvent.change(screen.getByLabelText("Источник"),{target:{value:"retrospective"}});fireEvent.change(screen.getByLabelText("ML version"),{target:{value:"ml_v1"}});fireEvent.change(screen.getByLabelText("Согласие"),{target:{value:"ml_dissent"}});await waitFor(()=>expect(api.getPredictionHistory).toHaveBeenLastCalledWith({tournamentId:7,date:"2026-08-30",status:"completed",source:"retrospective",comparisonType:"ml_dissent",mlModelVersion:"ml_v1"}))});
 it("expands saved factors, highlights the error driver and sends error filters",async()=>{const error_analysis={team_strength:{is_correct:true,margin:20},matchup:{status:"available" as const,is_correct:false,margin:10,strongest_driver:{factor:"map_veto",label:"Карты и вето",contribution:2.4,reliability:.2},error_drivers:[{factor:"map_veto",label:"Карты и вето",contribution:2.4,reliability:.2}],factors:[{factor:"map_veto",label:"Карты и вето",team_a_score:60,team_b_score:40,weight:.3,effective_weight:.3,reliability:.2,sample:2,available:true,raw_contribution:3,contribution:2.4,direction_winner_id:1,direction_correct:false,toward_predicted_winner:true}]},ml:{is_correct:true,probability:.57,confidence_margin:.07}};const data={...response,model_versions:{team_strength:["v2"],matchup:["matchup_v1"],ml:["ml_v1"]},statistics:{...response.statistics,matchup_factor_quality:{map_veto:{label:"Карты и вето",directional_cases:1,direction_correct:0,direction_accuracy:0,reliability:{low:{samples:1,direction_accuracy:0}},contribution_buckets:[]}},matchup_error_drivers:{map_veto:{top_driver_cases:1,present_in_error_cases:1}},ml_high_confidence_errors:{"65_plus":{predictions:1,errors:1,error_rate:1}}},items:[{...preMatch,error_analysis},retrospective]} as PredictionHistoryResponse;api.getPredictionHistory.mockResolvedValue(data);render(<PredictionHistoryPage/>);await screen.findByText("Matchup factor quality");fireEvent.click(screen.getAllByText("Разбор ошибки")[0]);expect(screen.getByText(/Главный фактор ошибки модели: Карты и вето/)).toBeTruthy();expect(screen.getByText(/объясняет решение модели, а не причину результата/)).toBeTruthy();fireEvent.change(screen.getByLabelText("Результат предикта"),{target:{value:"matchup"}});fireEvent.change(screen.getByLabelText("Главный фактор ошибки"),{target:{value:"map_veto"}});fireEvent.change(screen.getByLabelText("Matchup version"),{target:{value:"matchup_v1"}});fireEvent.change(screen.getByLabelText("ML ошибки"),{target:{value:"70"}});await waitFor(()=>expect(api.getPredictionHistory).toHaveBeenLastCalledWith(expect.objectContaining({errorResult:"matchup",matchupErrorDriver:"map_veto",matchupModelVersion:"matchup_v1",mlConfidenceError:70}))) });
});
