import {cleanup,fireEvent,render,screen,waitFor} from "@testing-library/react";
import {afterEach,describe,expect,it,vi} from "vitest";
import type {PredictionHistoryResponse} from "../types";

const api=vi.hoisted(()=>({getPredictionHistory:vi.fn()}));
vi.mock("../api",()=>api);
import {PredictionHistoryPage} from "./PredictionHistoryPage";
afterEach(()=>{cleanup();vi.clearAllMocks()});

const response:PredictionHistoryResponse={tournaments:[{id:7,name:"Test Cup"}],statistics:{team_strength:{correct:1,total:2,accuracy:.5},matchup:{correct:2,total:2,accuracy:1},ml:{correct:1,total:1,accuracy:1},consensus_3_3:{correct:1,total:1,accuracy:1},strong_conflict_threshold:10,conflicts:{ts_matchup_vs_ml:{total:0,majority_correct:0,dissent_correct:0,majority_accuracy:null,dissent_accuracy:null},ts_ml_vs_matchup:{total:1,majority_correct:1,dissent_correct:0,majority_accuracy:1,dissent_accuracy:0},matchup_ml_vs_ts:{total:0,majority_correct:0,dissent_correct:0,majority_accuracy:null,dissent_accuracy:null}}},items:[{id:1,match_id:160,tournament_id:7,tournament:"Test Cup",match_date:"2026-08-30",as_of:"2026-08-29T10:00:00Z",created_at:"2026-08-29T10:00:00Z",source:"retrospective",team_a:{id:1,name:"FURIA"},team_b:{id:2,name:"Legacy"},actual_winner_id:1,actual_winner:"FURIA",completed:true,team_strength:{team_a_value:60,team_b_value:40,predicted_winner_id:1,predicted_winner:"FURIA",correct:true,probability:false},matchup:{team_a_value:45,team_b_value:55,predicted_winner_id:2,predicted_winner:"Legacy",correct:false,probability:false},ml:{team_a_value:.57,team_b_value:.43,predicted_winner_id:1,predicted_winner:"FURIA",correct:true,probability:true},consensus:{winner_id:1,winner:"FURIA",votes:2,total:3,correct:true},conflict:{type:"ts_ml_vs_matchup",strength:16,strong:true,majority_winner_id:1,majority_winner:"FURIA",dissent_winner_id:2,dissent_winner:"Legacy",dissenting_prediction:"matchup"}}]};

describe("Prediction History",()=>{
 it("renders accuracy, result, predictions and match link",async()=>{api.getPredictionHistory.mockResolvedValue(response);render(<PredictionHistoryPage/>);expect((await screen.findByRole("link",{name:"FURIA vs Legacy"})).getAttribute("href")).toBe("/matches/160");expect(screen.getByText("✅ FURIA 57%")).toBeTruthy();expect(screen.getByText("❌ Legacy")).toBeTruthy();expect(screen.getByText("✅ 2/3 FURIA")).toBeTruthy();expect(screen.getByText("1 / 2")).toBeTruthy()});
 it("sends tournament, date, status and conflict filters",async()=>{api.getPredictionHistory.mockResolvedValue(response);render(<PredictionHistoryPage/>);await screen.findByText("FURIA vs Legacy");fireEvent.change(screen.getByLabelText("Турнир"),{target:{value:"7"}});fireEvent.change(screen.getByLabelText("Дата"),{target:{value:"2026-08-30"}});fireEvent.change(screen.getByLabelText("Статус"),{target:{value:"completed"}});fireEvent.click(screen.getByLabelText("Только 3/3 consensus"));fireEvent.click(screen.getByLabelText("Только расхождения"));fireEvent.change(screen.getByLabelText("Сила конфликта"),{target:{value:"strong"}});await waitFor(()=>expect(api.getPredictionHistory).toHaveBeenLastCalledWith({tournamentId:7,date:"2026-08-30",status:"completed",consensus:true,conflictOnly:true,strongConflicts:true}))});
});
